import { useEffect,useMemo,useState } from 'react';
import { CalendarDays,Clock3,Gauge,Pencil,TrendingUp } from 'lucide-react';
import Modal from '../../../components/ui/Modal';
import StatisticsPieChart from '../components/StatisticsPieChart';
import StatisticsStackedBarChart from '../components/StatisticsStackedBarChart';
import { activityTrackingService } from '../../../services/activityTrackingService';
import type { ActivityRange,StatisticsPeriodMode } from '../../../types/activityTracking';
type Mode='overview'|'charts'|'tables'|'availability'|'payroll';
const hhmm=(hours:number)=>{const mins=Math.round(hours*60);return `${Math.floor(mins/60)}:${String(mins%60).padStart(2,'0')}`};
const shortDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('he-IL',{day:'2-digit',month:'2-digit'});
const sundayOf=(value:string)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()-d.getDay());return d.toISOString().slice(0,10)};
export default function ActivityTrackingStatistics({jobTypeId,mode,selectedUserIds,rangeStart,rangeEnd,ranges,periodMode,canEdit=true,includeInactive=false}:{jobTypeId:string;mode:Mode;selectedUserIds:string[];rangeStart:string;rangeEnd:string;ranges?:Array<{start:string;end:string}>;periodMode:StatisticsPeriodMode;canEdit?:boolean;includeInactive?:boolean}){
 const[data,setData]=useState<ActivityRange|null>(null);const[error,setError]=useState<string|null>(null);const[editing,setEditing]=useState<ActivityRange['rows'][number]|null>(null);const[start,setStart]=useState('');const[end,setEnd]=useState('');const[reason,setReason]=useState('');
 const requestedRanges=ranges?.length?ranges:[{start:rangeStart,end:rangeEnd}];
 const loadRange=async()=>{const results=await Promise.all(requestedRanges.map(range=>activityTrackingService.getRange(jobTypeId,range.start,range.end,includeInactive)));return{rangeStart:requestedRanges[0].start,rangeEnd:requestedRanges[requestedRanges.length-1].end,rows:results.flatMap(result=>result.rows)} as ActivityRange};
 const reload=()=>loadRange().then(setData);
 const rangesKey=requestedRanges.map(range=>`${range.start}:${range.end}`).join('|');
 useEffect(()=>{let active=true;loadRange().then(x=>{if(active){setData(x);setError(null)}}).catch(e=>{if(active){setData(null);setError(e?.message??'')}});return()=>{active=false}},[jobTypeId,rangesKey,includeInactive]);
 const rows=useMemo(()=>selectedUserIds.length?(data?.rows??[]).filter(r=>selectedUserIds.includes(r.userId)):(data?.rows??[]),[data,selectedUserIds]);
 const totals=useMemo(()=>{const m=new Map<string,{key:string;label:string;value:number}>();for(const r of rows){const x=m.get(r.activityKey)??{key:r.activityKey,label:r.activityLabel,value:0};x.value+=Number(r.hours);m.set(r.activityKey,x)}return [...m.values()].sort((a,b)=>b.value-a.value)},[rows]);
 const total=totals.reduce((s,x)=>s+x.value,0);
 const workDays=useMemo(()=>new Set(rows.map(r=>`${r.userId}:${r.workDate}`)).size,[rows]);
 const avgPerDay=workDays?total/workDays:0;
 const dayTotals=useMemo(()=>{const m=new Map<string,number>();for(const r of rows)m.set(`${r.userId}:${r.workDate}`,(m.get(`${r.userId}:${r.workDate}`)??0)+Number(r.hours));return [...m.values()]},[rows]);
 const longestDay=dayTotals.length?Math.max(...dayTotals):0;
 const leading=totals[0];const leadingPct=total&&leading?Math.round(leading.value/total*100):0;
 const daily=useMemo(()=>{const m=new Map<string,Map<string,number>>();for(const r of rows){const d=m.get(r.workDate)??new Map<string,number>();d.set(r.activityLabel,(d.get(r.activityLabel)??0)+Number(r.hours));m.set(r.workDate,d)}return [...m].sort(([a],[b])=>a.localeCompare(b))},[rows]);
 const trend=useMemo(()=>{const series=new Map<string,string>();const buckets=new Map<string,{label:string;values:Record<string,number>}>();for(const r of rows){series.set(r.activityKey,r.activityLabel);let key=r.workDate,label=shortDate(r.workDate);if(periodMode==='month'){key=sundayOf(r.workDate);label=`שבוע ${shortDate(key)}`}else if(periodMode==='year'){key=r.workDate.slice(0,7);label=new Date(`${key}-01T12:00:00`).toLocaleDateString('he-IL',{month:'short'})}const b=buckets.get(key)??{label,values:{}};b.values[r.activityKey]=(b.values[r.activityKey]??0)+Number(r.hours);buckets.set(key,b)}return{series:[...series].map(([key,label])=>({key,label})),items:[...buckets].sort(([a],[b])=>a.localeCompare(b)).map(([key,b])=>({key,label:b.label,values:Object.fromEntries(Object.entries(b.values).map(([k,v])=>[k,Math.round(v*100)/100]))}))}},[rows,periodMode]);
 if(error?.includes('not allowed')||(!data&&!error))return null;if(!data)return null;
 const periodText=requestedRanges.length>1?`${requestedRanges.length} תקופות נבחרו`:`${new Date(`${rangeStart}T12:00:00`).toLocaleDateString('he-IL')} – ${new Date(`${rangeEnd}T12:00:00`).toLocaleDateString('he-IL')}`;
 const summary=<div className="statistics-summary-grid activity-kpi-grid"><article><Clock3 size={22}/><div><span>סה״כ זמן</span><strong>{hhmm(total)} שעות</strong></div></article><article><CalendarDays size={22}/><div><span>ימי עבודה מתועדים</span><strong>{workDays}</strong></div></article><article><Gauge size={22}/><div><span>ממוצע ליום עבודה</span><strong>{hhmm(avgPerDay)} שעות</strong></div></article><article><TrendingUp size={22}/><div><span>יום העבודה הארוך ביותר</span><strong>{hhmm(longestDay)} שעות</strong></div></article>{leading?<article><div><span>הפעילות המרכזית</span><strong>{leading.label} · {leadingPct}%</strong></div></article>:null}</div>;
 if(mode==='overview')return <section className="statistics-section activity-statistics"><header><div><h2>סיכום פעילות</h2><p>{periodText}</p></div></header>{summary}<div className="activity-overview-breakdown">{totals.map(x=><div key={x.key}><span>{x.label}</span><strong>{hhmm(x.value)} שעות</strong><small>{total?Math.round(x.value/total*100):0}% מהזמן</small></div>)}</div></section>;
 if(mode==='charts')return <section className="statistics-section activity-statistics"><header><div><h2>ניתוח פעילות</h2><p>{periodText}</p></div></header><div className="statistics-charts-grid"><StatisticsPieChart title="חלוקת זמן לפי פעילות" description="איזה חלק מזמן העבודה הושקע בכל תחום." slices={totals.map(x=>({label:x.label,value:Math.round(x.value*100)/100}))} valueFormatter={hhmm}/><StatisticsStackedBarChart title="מגמת פעילות לאורך התקופה" description={periodMode==='year'?'חלוקה חודשית לפי תחומי פעילות.':periodMode==='month'?'חלוקה שבועית לפי תחומי פעילות.':'חלוקה יומית לפי תחומי פעילות.'} series={trend.series} items={trend.items} unitLabel="שעות" valueFormatter={hhmm}/></div><div className="activity-daily-summary"><h3>פירוט יומי לפי פעילות</h3><p>סיכום נקי של הזמן בכל פעילות בכל יום, ללא פירוק למקטעים.</p>{daily.length?<table><thead><tr><th>תאריך</th><th>פעילות</th><th>זמן</th><th>חלק מהיום</th></tr></thead><tbody>{daily.flatMap(([date,items])=>{const dayTotal=[...items.values()].reduce((s,v)=>s+v,0);return [...items].map(([activity,hours],i)=><tr key={`${date}-${activity}`}><td>{i===0?new Date(`${date}T12:00:00`).toLocaleDateString('he-IL'):''}</td><td>{activity}</td><td>{hhmm(hours)}</td><td>{dayTotal?Math.round(hours/dayTotal*100):0}%</td></tr>)})}</tbody></table>:<p>אין נתוני פעילות בתקופה שנבחרה.</p>}</div></section>;
 if(mode!=='tables')return null;
 return <section className="statistics-section activity-statistics"><header><div><h2>מקטעי פעילות</h2><p>{periodText} · פירוט גולמי לצורך בקרה ועריכה.</p></div></header><div className="activity-week-table"><table><thead><tr><th>עובד</th><th>תאריך</th><th>פעילות</th><th>זמן</th><th>מקטע</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.segmentId}><td>{r.displayName}</td><td>{r.workDate}</td><td>{r.activityLabel}</td><td>{hhmm(Number(r.hours))}</td><td><bdi dir="ltr">{new Date(r.startedAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'})}–{r.endedAt?new Date(r.endedAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}):'פעיל'}</bdi>{r.status==='needs_review'?<span> · דורש בדיקה</span>:null}</td><td>{canEdit?<button title="עריכת מקטע" onClick={()=>{setEditing(r);setStart(r.startedAt.slice(0,16));setEnd((r.endedAt??new Date().toISOString()).slice(0,16));setReason('')}}><Pencil size={15}/></button>:null}</td></tr>)}</tbody></table></div>{editing?<Modal isOpen title="עריכת מקטע פעילות" onClose={()=>setEditing(null)}><div className="activity-edit-form"><label>פעילות<select value={editing.activityKey} onChange={e=>{const label=e.target.options[e.target.selectedIndex].text;setEditing({...editing,activityKey:e.target.value,activityLabel:label})}}>{Array.from(new Map((data.rows??[]).map(r=>[r.activityKey,r.activityLabel]))).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>התחלה<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>סיום<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>סיבת שינוי<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button onClick={async()=>{try{await activityTrackingService.updateSegment(editing.segmentId,editing.activityKey,new Date(start).toISOString(),new Date(end).toISOString(),reason);setEditing(null);await reload()}catch(e:any){alert(e?.message??'העריכה נכשלה')}}}>שמור שינוי</button></div></Modal>:null}</section>
}
