import { useEffect, useMemo, useState } from 'react';
import { Mail, MessageCircle, Pencil, Phone, Plus, Search, Upload, X } from 'lucide-react';
import * as XLSX from 'xlsx';
import { useAuth } from '../auth/AuthContext';
import { contactsService } from '../services/contactsService';
import type { ContactImportRow } from '../types/contacts';
import type { ContactRecord, EmployeeContact } from '../types/contacts';
import '../styles/contacts.css';

const label={current:'איש הקשר מעודכן',new:'איש קשר חדש!',updated:'איש קשר עודכן',needs_review:'דורש בדיקה'} as const;
function normalizePhone(value:unknown){const raw=String(value??'').replace(/[\u200e\u200f\u202a-\u202e]/g,'').trim();if(!raw)return {phone:null,review:false};let d=raw.replace(/\D/g,'');if(d.startsWith('972'))d=d.slice(3);if(d.length===9&&d.startsWith('5'))d='0'+d;if(d.length===10&&d.startsWith('05'))return {phone:'+972'+d.slice(1),review:false};return {phone:raw,review:true};}
function parseOsherAd(file:ArrayBuffer):ContactImportRow[]{const wb=XLSX.read(file,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const a=XLSX.utils.sheet_to_json<any[]>(ws,{header:1,raw:false,defval:''});const rows:ContactImportRow[]=[];const general=String(a[1]?.[1]??'');const m=general.match(/מנהל אגף טכני\s*-\s*(.*?)\s*-\s*([+\d][\d\- ]+)/);if(m){const p=normalizePhone(m[2]);rows.push({branchName:null,roleName:'מנהל אגף טכני',fullName:m[1].trim(),phone:p.phone,email:null,sourceRow:2,needsReview:p.review});}for(let i=4;i<a.length;i++){const r=a[i];const branch=String(r?.[0]??'').trim();if(!branch)continue;const defs:Array<[number,string,number,number|null]>=[[1,'מנהל סניף',3,2],[4,'סגן מנהל',5,null],[6,'מנהל מחלקת קפואים',7,null],[8,'אחראי משמרת ערב',9,null]];for(const [nameCol,role,phoneCol,emailCol] of defs){const name=String(r[nameCol]??'').trim();if(!name)continue;const p=normalizePhone(r[phoneCol]);rows.push({branchName:branch,roleName:role,fullName:name,phone:p.phone,email:emailCol===null?null:String(r[emailCol]??'').trim()||null,sourceRow:i+1,needsReview:p.review});}}return rows;}

type NewContactForm={clientId:string;newClientName:string;branchName:string;newBranchName:string;roleName:string;fullName:string;phone:string;email:string};
const NEW_CLIENT='__new_client__'; const NEW_BRANCH='__new_branch__';
const emptyForm:NewContactForm={clientId:'',newClientName:'',branchName:'',newBranchName:'',roleName:'',fullName:'',phone:'',email:''};

export default function ContactsPage(){
 const {hasPermission}=useAuth();
 const [mode,setMode]=useState<'clients'|'employees'>('clients');
 const [contacts,setContacts]=useState<ContactRecord[]>([]); const [employees,setEmployees]=useState<EmployeeContact[]>([]);
 const [clients,setClients]=useState<{id:string;name:string}[]>([]); const [client,setClient]=useState(''); const [branch,setBranch]=useState('');
 const [q,setQ]=useState(''); const [busy,setBusy]=useState(false); const [adding,setAdding]=useState(false); const [editing,setEditing]=useState<ContactRecord|null>(null); const [form,setForm]=useState<NewContactForm>(emptyForm);
 const load=async()=>{const [c,e,cl]=await Promise.all([contactsService.listContacts(),contactsService.listEmployees(),contactsService.listClients()]);setContacts(c);setEmployees(e);setClients(cl);};
 useEffect(()=>{void load();},[]);
 useEffect(()=>{setBranch('');},[client]);
 const clientContacts=useMemo(()=>client?contacts.filter(x=>x.clientId===client):contacts,[contacts,client]);
 const branches=useMemo(()=>Array.from(new Set(clientContacts.map(x=>x.branchName).filter((x):x is string=>Boolean(x)))).sort((a,b)=>a.localeCompare(b,'he')),[clientContacts]);
 const filtered=useMemo(()=>clientContacts.filter(x=>(!branch||x.branchName===branch)&&`${x.branchName??''} ${x.fullName} ${x.roleName} ${x.email??''} ${x.phone??''}`.toLocaleLowerCase('he').includes(q.trim().toLocaleLowerCase('he'))),[clientContacts,branch,q]);
 const importFile=async(f:File)=>{setBusy(true);try{const rows=parseOsherAd(await f.arrayBuffer());const result=await contactsService.importRows('אושר עד',f.name,rows);alert(`הייבוא הושלם: ${result.added} חדשים, ${result.updated} עודכנו, ${result.unchanged} ללא שינוי, ${result.needsReview} לבדיקה.`);await load();}catch(e:any){alert(e?.message??'ייבוא הקובץ נכשל');}finally{setBusy(false);}};
 const actions=(phone:string|null,email:string|null)=><span className="contact-actions">{phone&&<><a href={`https://wa.me/${phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" title="WhatsApp"><MessageCircle size={17}/></a><a href={`tel:${phone}`} title="חיוג"><Phone size={17}/></a></>}{email&&<a href={`mailto:${email}`} title="מייל"><Mail size={17}/></a>}</span>;
 const openAdd=()=>{const chosen=client||clients[0]?.id||'';setEditing(null);setForm({...emptyForm,clientId:chosen,branchName:branch});setAdding(true);};
 const openEdit=(c:ContactRecord)=>{setEditing(c);setForm({...emptyForm,clientId:c.clientId,branchName:c.branchName??'',roleName:c.roleName,fullName:c.fullName,phone:c.phone??'',email:c.email??''});setAdding(true);};
 const formBranches=useMemo(()=>Array.from(new Set(contacts.filter(c=>c.clientId===form.clientId&&c.branchName).map(c=>c.branchName!))).sort((a,b)=>a.localeCompare(b,'he')),[contacts,form.clientId]);
 const saveContact=async()=>{if(!form.fullName.trim()||!form.roleName.trim()){alert('יש למלא שם ותפקיד.');return;} if(!form.clientId){alert('יש לבחור לקוח.');return;} setBusy(true);try{let clientId=form.clientId;if(clientId===NEW_CLIENT){if(!form.newClientName.trim()){alert('יש להזין שם לקוח חדש.');return;}clientId=await contactsService.createClient(form.newClientName.trim());} const branchName=form.branchName===NEW_BRANCH?form.newBranchName.trim():form.branchName.trim(); if(form.branchName===NEW_BRANCH&&!branchName){alert('יש להזין שם סניף חדש.');return;} const normalized=form.phone.trim()?normalizePhone(form.phone):{phone:null,review:false}; const payload={clientId,branchName:branchName||null,roleName:form.roleName.trim(),fullName:form.fullName.trim(),phone:normalized.phone,email:form.email.trim()||null,needsReview:normalized.review}; if(editing)await contactsService.updateContact({id:editing.id,...payload});else await contactsService.createContact(payload);setAdding(false);setEditing(null);await load();if(clientId!==NEW_CLIENT)setClient(clientId);}catch(e:any){alert(e?.message??'שמירת איש הקשר נכשלה');}finally{setBusy(false);}};
 return <main className="contacts-page" dir="rtl"><header><div><h1>אנשי קשר</h1><p>ספר אנשי הקשר של לקוחות ועובדי המערכת.</p></div><div className="contacts-header-actions">{hasPermission('contacts.edit')&&<button className="contacts-add" onClick={openAdd}><Plus size={17}/>הוספת איש קשר</button>}{hasPermission('contacts.import')&&<label className="contacts-import"><Upload size={17}/>{busy?'מייבא…':'העלאת אושר עד'}<input type="file" accept=".xlsx,.xls" disabled={busy} onChange={e=>e.target.files?.[0]&&void importFile(e.target.files[0])}/></label>}</div></header>
 <div className="contacts-tabs"><button className={mode==='clients'?'active':''} onClick={()=>setMode('clients')}>לקוחות</button><button className={mode==='employees'?'active':''} onClick={()=>setMode('employees')}>עובדים</button></div>
 {mode==='clients'&&<div className="contact-filter-levels"><div className="contact-chip-row"><button className={!client?'active':''} onClick={()=>setClient('')}>כל הלקוחות</button>{clients.map(c=><button key={c.id} className={client===c.id?'active':''} onClick={()=>setClient(c.id)}>{c.name}</button>)}</div>{client&&<div className="contact-chip-row branch-chips"><button className={!branch?'active':''} onClick={()=>setBranch('')}>כל הסניפים</button>{branches.map(b=><button key={b} className={branch===b?'active':''} onClick={()=>setBranch(b)}>{b}</button>)}</div>}</div>}
 <div className="contacts-filters"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={mode==='clients'?'חיפוש לפי שם, סניף, תפקיד, טלפון או מייל…':'חיפוש עובד או תפקיד…'}/></div>
 {mode==='clients'?<div className="contact-branches">{Array.from(new Set(filtered.map(c=>c.branchName??'אנשי קשר כלליים'))).map(b=><section className="contact-branch" key={b}><h2>{b}</h2><div className="contact-grid">{filtered.filter(c=>(c.branchName??'אנשי קשר כלליים')===b).map(c=><article className="contact-card" key={c.id}><div><b>{c.fullName}</b><span>{c.roleName}</span></div><span className={`contact-status ${c.changeStatus}`}>{label[c.changeStatus]}</span>{c.phone&&<bdi dir="ltr">{c.phone}</bdi>}{c.email&&<small>{c.email}</small>}<footer>{actions(c.phone,c.email)}{hasPermission('contacts.edit')&&<button title="עריכה" onClick={()=>openEdit(c)}><Pencil size={17}/></button>}</footer></article>)}</div></section>)}</div>:<div className="contact-grid employee-grid">{employees.filter(e=>`${e.displayName} ${e.scheduleName??''} ${e.roleLabel}`.includes(q)).map(e=><article className="contact-card" key={e.id}><div><b>{e.displayName}</b><span>{e.roleLabel}</span></div>{e.scheduleName&&<small>שם שיבוץ: {e.scheduleName}</small>}{e.phone?<><bdi dir="ltr">{e.phone}</bdi>{actions(e.phone,null)}</>:<small>לא הוגדר מספר טלפון</small>}{hasPermission('contacts.edit')&&<button className="employee-phone-edit" onClick={async()=>{const p=prompt('מספר טלפון',e.phone??'');if(p===null)return;const n=normalizePhone(p);await contactsService.updateEmployeePhone(e.id,n.phone);await load();}}><Pencil size={16}/> עריכת טלפון</button>}</article>)}</div>}
 {adding&&<div className="contact-modal-backdrop" onMouseDown={()=>{setAdding(false);setEditing(null);}}><section className="contact-modal" onMouseDown={e=>e.stopPropagation()}><header><div><h2>{editing?'עריכת איש קשר':'הוספת איש קשר'}</h2><p>בחר לקוח קיים או צור לקוח חדש. ניתן לשייך לסניף קיים, ליצור סניף חדש או להשאיר ללא סניף.</p></div><button onClick={()=>{setAdding(false);setEditing(null);}}><X size={20}/></button></header><div className="contact-form">
 <label>לקוח<select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value,newClientName:'',branchName:'',newBranchName:''})}><option value="">בחר לקוח</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}<option value={NEW_CLIENT}>＋ הוסף לקוח חדש</option></select></label>
 {form.clientId===NEW_CLIENT&&<label>שם לקוח חדש<input autoFocus value={form.newClientName} onChange={e=>setForm({...form,newClientName:e.target.value})} placeholder="שם הלקוח"/></label>}
 {form.clientId&&form.clientId!==NEW_CLIENT&&<label>סניף (אופציונלי)<select value={form.branchName} onChange={e=>setForm({...form,branchName:e.target.value,newBranchName:''})}><option value="">ללא סניף</option>{formBranches.map(b=><option key={b} value={b}>{b}</option>)}<option value={NEW_BRANCH}>＋ הוסף סניף חדש</option></select></label>}
 {form.clientId===NEW_CLIENT&&<label>סניף (אופציונלי)<select value={form.branchName} onChange={e=>setForm({...form,branchName:e.target.value,newBranchName:''})}><option value="">ללא סניף</option><option value={NEW_BRANCH}>＋ הוסף סניף חדש</option></select></label>}
 {form.branchName===NEW_BRANCH&&<label>שם סניף חדש<input value={form.newBranchName} onChange={e=>setForm({...form,newBranchName:e.target.value})} placeholder="שם הסניף"/></label>}
 <label>שם איש קשר<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>תפקיד<input value={form.roleName} onChange={e=>setForm({...form,roleName:e.target.value})}/></label><label>טלפון<input dir="ltr" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="05... או +972..."/></label><label>מייל (אופציונלי)<input dir="ltr" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><footer><button onClick={()=>{setAdding(false);setEditing(null);}}>ביטול</button><button className="primary" disabled={busy} onClick={()=>void saveContact()}>{busy?'שומר…':editing?'שמור שינויים':'הוסף איש קשר'}</button></footer></section></div>}
 </main>;
}
