import { useCallback,useEffect,useState } from 'react';
import { CheckCircle2,Clock3,Pause,Play } from 'lucide-react';
import { activityTrackingService } from '../../services/activityTrackingService';
import type { ActivityRoleContext } from '../../types/activityTracking';
const seconds=(a:string,b:string)=>Math.max(0,(new Date(b).getTime()-new Date(a).getTime())/1000);
const fmt=(s:number)=>{const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=Math.floor(s%60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`};
const endTime=(value:string|null|undefined)=>value?new Date(value).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}):null;
export default function ActivityTrackingCards(){const[roles,setRoles]=useState<ActivityRoleContext[]>([]);const[busy,setBusy]=useState<string|null>(null);const[now,setNow]=useState(Date.now());
 const load=useCallback(()=>activityTrackingService.getMyContext().then(setRoles).catch(e=>console.error('Activity tracking dashboard failed:',e)),[]);
 useEffect(()=>{void load();const i=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(i)},[load]);
 const switchTo=async(r:ActivityRoleContext,key:string)=>{const open=r.day?.segments.find(s=>!s.endedAt);setBusy(r.jobTypeId);try{if(open?.activityKey===key){await activityTrackingService.pauseActivity(r.jobTypeId);}else{if(r.day?.status==='ended'&&!window.confirm(`יום העבודה כבר הסתיים${r.day.endedAt?` ב-${endTime(r.day.endedAt)}`:''}. להתחיל פעילות מחדש?`))return;await activityTrackingService.switchActivity(r.jobTypeId,key)}await load()}finally{setBusy(null)}};
 const finish=async(j:string)=>{setBusy(j);try{await activityTrackingService.endDay(j);await load()}finally{setBusy(null)}};
 if(!roles.length)return null;
 return <div className="activity-tracking-grid">{roles.map(r=>{const open=r.day?.segments.find(s=>!s.endedAt);const totals=new Map<string,number>();for(const s of r.day?.segments??[]){totals.set(s.activityKey,(totals.get(s.activityKey)??0)+seconds(s.startedAt,s.endedAt??new Date(now).toISOString()))}const total=Array.from(totals.values()).reduce((a,b)=>a+b,0);const ended=r.day?.status==='ended';return <section className="dashboard-card activity-tracking-card" key={r.jobTypeId}><div className="dashboard-card-header"><div><h2>מעקב פעילות · {r.jobTypeName}</h2><span>{r.day?.status==='needs_review'?'דורש בדיקה':open?`פעיל עכשיו · ${open.activityLabel}`:ended?`יום העבודה הסתיים ב-${endTime(r.day?.endedAt)}`:'מוכן להתחלה'}</span></div><Clock3 size={20}/></div><div className="dashboard-card-body"><strong className="activity-main-timer">{fmt(total)}</strong>{ended?<div className="activity-ended-banner"><CheckCircle2 size={18}/><div><strong>יום העבודה הסתיים ב-{endTime(r.day?.endedAt)}</strong><span>סה״כ היום {fmt(total)}</span></div></div>:null}<div className="activity-buttons activity-action-cards">{r.activities.map(a=>{const active=open?.activityKey===a.key;return <button key={a.key} disabled={busy===r.jobTypeId} className={active?'active':''} onClick={()=>void switchTo(r,a.key)}>{active?<Pause size={22}/>:<Play size={22}/>}<span>{a.label}</span><small>{fmt(totals.get(a.key)??0)} היום</small>{active?<em>פעיל עכשיו · לחץ להשהיה</em>:null}</button>})}</div><button className="activity-end-day-button" disabled={busy===r.jobTypeId||!r.day||ended} onClick={()=>void finish(r.jobTypeId)}><CheckCircle2 size={18}/>{ended?'היום הסתיים':'סיום יום'}</button>{r.effectiveSettings?<small className="activity-reminder-note">{r.effectiveSettings.autoEndEnabled?`סיום אוטומטי: ${r.effectiveSettings.autoEndTime}`:'סיום אוטומטי כבוי'} · {r.effectiveSettings.continuousReminderEnabled?`התראת פעילות רציפה אחרי ${Math.round(r.effectiveSettings.continuousReminderMinutes/60*10)/10} שעות`:'התראת פעילות רציפה כבויה'}</small>:r.reminderEnabled?<small className="activity-reminder-note">תזכורת לסיום יום: {r.reminderTime}</small>:null}</div></section>})}</div>}
