-- Phase 10.3: dynamic operational permission enforcement.
-- Replaces legacy users.manage/users.view guards on the Dynamic-first scheduling flow
-- with Job-Type-scoped permissions generated by the dynamic permission engine.

begin;

create or replace function public.create_dynamic_availability_shadow_period(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid:=auth.uid();
  target_job public.job_types%rowtype;
  target_period_id uuid;
  effective_config jsonb;
  created_slots integer:=0;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;
  if not public.has_dynamic_job_type_permission('availability.open_period', requested_job_type_id, current_user_id) then
    raise exception 'not allowed';
  end if;
  if requested_year not between 2020 and 2100 or requested_month not between 1 and 12 then
    raise exception 'invalid year or month';
  end if;

  select * into target_job from public.job_types where id=requested_job_type_id;
  if target_job.id is null then raise exception 'job type not found'; end if;

  select m.source_snapshot into effective_config
  from public.job_type_schedule_materializations m
  where m.job_type_id=target_job.id
    and m.effective_month<=make_date(requested_year,requested_month,1)
  order by m.effective_month desc
  limit 1;

  if effective_config is null then
    raise exception 'no effective role configuration exists for this month';
  end if;

  if coalesce((effective_config#>>'{availabilityConfig,enabled}')::boolean,
              (target_job.availability_config->>'enabled')::boolean,
              false) is not true then
    raise exception 'availability is disabled for job type';
  end if;

  insert into public.dynamic_availability_periods(
    schedule_group_id,job_type_id,year,month,title,status,config_snapshot,source,created_by
  ) values(
    target_job.schedule_group_id,
    target_job.id,
    requested_year,
    requested_month,
    target_job.name || ' · ' || requested_month || '/' || requested_year,
    'shadow',
    coalesce(effective_config->'availabilityConfig',target_job.availability_config,'{}'::jsonb),
    'dynamic_role',
    current_user_id
  )
  on conflict(job_type_id,year,month) do update set
    schedule_group_id=excluded.schedule_group_id,
    config_snapshot=excluded.config_snapshot,
    updated_at=now()
  returning id into target_period_id;

  created_slots := public.materialize_dynamic_availability_period_slots(target_period_id);

  return jsonb_build_object(
    'periodId',target_period_id,
    'createdSlots',created_slots,
    'slotCount',(select count(*) from public.dynamic_availability_slots s where s.period_id=target_period_id),
    'mode','dynamic_role'
  );
end;
$function$;

create or replace function public.set_dynamic_period_status(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer,
  requested_action text
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid:=auth.uid();
  target_period public.dynamic_availability_periods%rowtype;
  next_status text;
  slot_count integer:=0;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;
  if requested_action = 'open' then
    if not public.has_dynamic_job_type_permission('availability.open_period', requested_job_type_id, current_user_id) then raise exception 'not allowed'; end if;
  elsif requested_action in ('close','archive') then
    if not public.has_dynamic_job_type_permission('availability.close_period', requested_job_type_id, current_user_id) then raise exception 'not allowed'; end if;
  else
    raise exception 'invalid period action';
  end if;

  select * into target_period
  from public.dynamic_availability_periods
  where job_type_id=requested_job_type_id and year=requested_year and month=requested_month;

  if target_period.id is null then raise exception 'dynamic period not found'; end if;

  if requested_action='open' and target_period.status in ('shadow','draft','closed','open') then
    -- Ensure the employee-facing month is populated before it becomes usable.
    perform public.materialize_dynamic_availability_period_slots(target_period.id);
    next_status:='open';
  elsif requested_action='close' and target_period.status='open' then
    next_status:='closed';
  elsif requested_action='archive' and target_period.status='closed' and exists(
    select 1 from public.dynamic_schedule_publications p
    where p.job_type_id=requested_job_type_id and p.year=requested_year and p.month=requested_month
  ) then
    next_status:='archived';
  else
    raise exception 'invalid period transition from % using %',target_period.status,requested_action;
  end if;

  update public.dynamic_availability_periods
  set status=next_status,updated_at=now()
  where id=target_period.id;

  select count(*) into slot_count
  from public.dynamic_availability_slots
  where period_id=target_period.id;

  return jsonb_build_object(
    'periodId',target_period.id,
    'status',next_status,
    'action',requested_action,
    'slotCount',slot_count
  );
end;
$function$;

create or replace function public.get_dynamic_period_workflow(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid := auth.uid();
  target_job public.job_types%rowtype;
  target_period public.dynamic_availability_periods%rowtype;
  latest_draft public.dynamic_schedule_shadow_drafts%rowtype;
  publication public.dynamic_schedule_publications%rowtype;
  member_count integer := 0;
  slot_count integer := 0;
  submission_count integer := 0;
  submitted_count integer := 0;
  assignment_count integer := 0;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;
  if not (
    public.has_dynamic_job_type_permission('availability.view_team', requested_job_type_id, current_user_id)
    or public.has_dynamic_job_type_permission('schedule.view_team', requested_job_type_id, current_user_id)
  ) then raise exception 'not allowed'; end if;
  if requested_month not between 1 and 12 then raise exception 'invalid month'; end if;

  select * into target_job from public.job_types where id=requested_job_type_id;
  if target_job.id is null then raise exception 'job type not found'; end if;

  select count(*) into member_count
  from public.job_type_memberships m
  join public.profiles p on p.id=m.user_id
  where m.job_type_id=target_job.id and p.is_active=true;

  select * into target_period
  from public.dynamic_availability_periods
  where job_type_id=target_job.id and year=requested_year and month=requested_month;

  if target_period.id is not null then
    select count(*) into slot_count from public.dynamic_availability_slots where period_id=target_period.id;
    select count(*), count(*) filter (where status='submitted')
      into submission_count, submitted_count
    from public.dynamic_availability_submissions where period_id=target_period.id;

    select * into latest_draft
    from public.dynamic_schedule_shadow_drafts
    where job_type_id=target_job.id and year=requested_year and month=requested_month
    order by created_at desc limit 1;
  end if;

  select * into publication
  from public.dynamic_schedule_publications
  where job_type_id=target_job.id and year=requested_year and month=requested_month;

  if publication.id is not null then
    select count(*) into assignment_count
    from public.dynamic_schedule_published_assignments where publication_id=publication.id;
  end if;

  return jsonb_build_object(
    'jobTypeId', target_job.id,
    'jobTypeName', target_job.name,
    'year', requested_year,
    'month', requested_month,
    'memberCount', member_count,
    'availabilityEnabled', coalesce((target_job.availability_config->>'enabled')::boolean,false),
    'schedulingStrategy', coalesce(target_job.scheduling_strategy, target_job.scheduling_config->>'schedulingStrategy','availability_optimizer'),
    'permissions', jsonb_build_object(
      'availability.view_team', public.has_dynamic_job_type_permission('availability.view_team', target_job.id, current_user_id),
      'availability.open_period', public.has_dynamic_job_type_permission('availability.open_period', target_job.id, current_user_id),
      'availability.close_period', public.has_dynamic_job_type_permission('availability.close_period', target_job.id, current_user_id),
      'availability.manage_submissions', public.has_dynamic_job_type_permission('availability.manage_submissions', target_job.id, current_user_id),
      'schedule.view_team', public.has_dynamic_job_type_permission('schedule.view_team', target_job.id, current_user_id),
      'schedule.create_draft', public.has_dynamic_job_type_permission('schedule.create_draft', target_job.id, current_user_id),
      'schedule.edit_draft', public.has_dynamic_job_type_permission('schedule.edit_draft', target_job.id, current_user_id),
      'schedule.publish', public.has_dynamic_job_type_permission('schedule.publish', target_job.id, current_user_id),
      'schedule.edit_published', public.has_dynamic_job_type_permission('schedule.edit_published', target_job.id, current_user_id),
      'rotation.generate', public.has_dynamic_job_type_permission('rotation.generate', target_job.id, current_user_id)
    ),
    'period', case when target_period.id is null then null else jsonb_build_object(
      'id',target_period.id,'status',target_period.status,'title',target_period.title,
      'submissionDeadline',target_period.submission_deadline,'slotCount',slot_count,
      'submissionCount',submission_count,'submittedCount',submitted_count
    ) end,
    'draft', case when latest_draft.id is null then null else jsonb_build_object(
      'id',latest_draft.id,'status',latest_draft.status,'metrics',latest_draft.metrics,
      'createdAt',latest_draft.created_at,'updatedAt',latest_draft.updated_at
    ) end,
    'publication', case when publication.id is null then null else jsonb_build_object(
      'id',publication.id,'status',publication.status,'publishedAt',publication.published_at,
      'assignmentCount',assignment_count
    ) end
  );
end;
$function$;

create or replace function public.create_dynamic_schedule_shadow_draft(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid := auth.uid();
  job public.job_types%rowtype;
  period public.dynamic_availability_periods%rowtype;
  v_draft_id uuid;
  feasibility jsonb;
  sl record;
  chosen_user uuid;
  chosen_score numeric;
  chosen_status text;
  chosen_assigned integer;
  chosen_min integer;
  chosen_target integer;
  chosen_max integer;
  assigned_required integer := 0;
  assigned_optional integer := 0;
  unfilled integer := 0;
  avoid_assignments integer := 0;
  above_target_assignments integer := 0;
  no_consecutive boolean;
  max_per_day integer;
  min_rest integer;
  max_hard boolean;
  coverage_weight numeric;
  fairness_weight numeric;
  preference_weight numeric;
  optional_weight numeric;
  blocked_slots uuid[] := array[]::uuid[];
  remaining_positions integer;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;
  if not public.has_dynamic_job_type_permission('schedule.create_draft', requested_job_type_id, current_user_id) then raise exception 'not allowed'; end if;
  select * into job from public.job_types where id=requested_job_type_id;
  if job.id is null then raise exception 'job type not found'; end if;
  select * into period from public.dynamic_availability_periods where job_type_id=job.id and year=requested_year and month=requested_month;
  if period.id is null then raise exception 'shadow availability period not found'; end if;

  feasibility := public.analyze_dynamic_schedule_feasibility(job.id,requested_year,requested_month);
  no_consecutive := coalesce((job.scheduling_config#>>'{rules,noConsecutive,enabled}')::boolean,true);
  max_per_day := case when coalesce((job.scheduling_config#>>'{rules,maxShiftsPerDay,enabled}')::boolean,true) then coalesce((job.scheduling_config#>>'{rules,maxShiftsPerDay,value}')::integer,1) else 999 end;
  min_rest := case when coalesce((job.scheduling_config#>>'{rules,minimumRestMinutes,enabled}')::boolean,false) then coalesce((job.scheduling_config#>>'{rules,minimumRestMinutes,value}')::integer,0) else 0 end;
  max_hard := coalesce(job.scheduling_config->>'maximumMode','hard')='hard';
  coverage_weight := coalesce((job.scheduling_config#>>'{weights,coverage}')::numeric,1000);
  fairness_weight := coalesce((job.scheduling_config#>>'{weights,proportionalFairness}')::numeric,100);
  preference_weight := coalesce((job.scheduling_config#>>'{weights,preference}')::numeric,30);
  optional_weight := coalesce((job.scheduling_config#>>'{weights,targetOptional}')::numeric,15);

  insert into public.dynamic_schedule_shadow_drafts(job_type_id,availability_period_id,year,month,status,feasibility_snapshot,rules_snapshot,created_by)
  values(job.id,period.id,requested_year,requested_month,'shadow',feasibility,job.scheduling_config,current_user_id)
  returning id into v_draft_id;

  insert into public.dynamic_schedule_shadow_targets(
    draft_id,user_id,requested_min,requested_target,requested_max,available_slots,
    proportional_weight,proportional_target,employment_scope,employment_factor
  )
  select
    v_draft_id,(m->>'userId')::uuid,(m->>'minimum')::integer,(m->>'target')::integer,
    nullif(m->>'maximum','')::integer,(m->>'availableSlots')::integer,
    coalesce((m->>'weight')::numeric,1),coalesce((m->>'proportionalTarget')::numeric,0),
    nullif(m->>'employmentScope',''),coalesce((m->>'employmentFactor')::numeric,1)
  from jsonb_array_elements(coalesce(feasibility->'members','[]'::jsonb)) m;

  loop
    select candidate_slot.* into sl
    from public.dynamic_availability_slots candidate_slot
    where candidate_slot.period_id=period.id
      and not (candidate_slot.id = any(blocked_slots))
      and (select count(*) from public.dynamic_schedule_shadow_assignments a
           where a.draft_id=v_draft_id and a.slot_id=candidate_slot.id and a.assignment_tier='required') < candidate_slot.min_workers
    order by
      (select count(*) from public.dynamic_schedule_shadow_targets t
       join public.dynamic_availability_submissions sub on sub.period_id=period.id and sub.user_id=t.user_id
       join public.dynamic_availability_entries e on e.submission_id=sub.id and e.slot_id=candidate_slot.id and e.availability_status in ('preferred','available','avoid')
       where t.draft_id=v_draft_id
         and (not max_hard or t.requested_max is null or t.assigned_count<t.requested_max)
         and public.dynamic_shadow_candidate_allowed(v_draft_id,t.user_id,candidate_slot.id,max_per_day,no_consecutive,min_rest)) asc,
      candidate_slot.shift_date,candidate_slot.start_time,candidate_slot.id
    limit 1;
    exit when not found;

    chosen_user:=null; chosen_score:=null; chosen_status:=null; chosen_assigned:=null; chosen_min:=null; chosen_target:=null; chosen_max:=null;

    select c.user_id,c.score,c.availability_status,c.assigned_count,c.requested_min,c.requested_target,c.requested_max
    into chosen_user,chosen_score,chosen_status,chosen_assigned,chosen_min,chosen_target,chosen_max
    from (
      select t.user_id,t.assigned_count,t.requested_min,t.requested_target,t.requested_max,e.availability_status,
        coverage_weight
        + greatest(t.requested_min-t.assigned_count,0)*fairness_weight*2
        -- Employment factor changes balancing pressure only. It never removes eligibility.
        + greatest(t.requested_target-t.assigned_count,0)*fairness_weight*t.employment_factor
        + greatest(t.proportional_target-t.assigned_count,0)*fairness_weight*0.5
        + case e.availability_status when 'preferred' then preference_weight when 'available' then 0 when 'avoid' then -preference_weight*4 else -1000000 end
        + case when not max_hard and t.requested_max is not null and t.assigned_count>=t.requested_max
            then -fairness_weight*4*(t.assigned_count-t.requested_max+1) else 0 end as score
      from public.dynamic_schedule_shadow_targets t
      join public.dynamic_availability_submissions sub on sub.period_id=period.id and sub.user_id=t.user_id
      join public.dynamic_availability_entries e on e.submission_id=sub.id and e.slot_id=sl.id and e.availability_status in ('preferred','available','avoid')
      where t.draft_id=v_draft_id
        and (not max_hard or t.requested_max is null or t.assigned_count<t.requested_max)
        and public.dynamic_shadow_candidate_allowed(v_draft_id,t.user_id,sl.id,max_per_day,no_consecutive,min_rest)
      order by score desc,t.assigned_count asc,t.user_id limit 1
    ) c;

    if chosen_user is null then
      select greatest(sl.min_workers-count(*),0) into remaining_positions
      from public.dynamic_schedule_shadow_assignments a
      where a.draft_id=v_draft_id and a.slot_id=sl.id and a.assignment_tier='required';
      unfilled:=unfilled+remaining_positions;
      blocked_slots:=array_append(blocked_slots,sl.id);
      continue;
    end if;

    insert into public.dynamic_schedule_shadow_assignments(draft_id,slot_id,user_id,assignment_tier,score,reasons)
    values(v_draft_id,sl.id,chosen_user,'required',chosen_score,jsonb_build_array(
      'כיסוי משמרת','קדימות למשמרות עם מעט מועמדים',
      case when chosen_assigned<coalesce(chosen_min,0) then 'השלמת מינימום חודשי'
           when chosen_assigned<coalesce(chosen_target,0) then 'איזון לכיוון היעד החודשי'
           else 'העובד נשאר מועמד גם לאחר הגעה ליעד' end,
      case chosen_status when 'preferred' then 'מעדיף' when 'available' then 'זמין' when 'avoid' then 'מעדיף שלא — נבחר רק לאחר שקלול עדיפות נמוכה' else chosen_status end
    ));
    update public.dynamic_schedule_shadow_targets t set assigned_count=t.assigned_count+1
    where t.draft_id=v_draft_id and t.user_id=chosen_user;
    if chosen_status='avoid' then avoid_assignments:=avoid_assignments+1; end if;
    if chosen_assigned>=coalesce(chosen_target,0) then above_target_assignments:=above_target_assignments+1; end if;
    assigned_required:=assigned_required+1;
  end loop;

  for sl in select * from public.dynamic_availability_slots s where s.period_id=period.id and s.target_workers>s.min_workers order by s.shift_date,s.start_time,s.id loop
    loop
      exit when (select count(*) from public.dynamic_schedule_shadow_assignments a where a.draft_id=v_draft_id and a.slot_id=sl.id)>=sl.target_workers;
      chosen_user:=null; chosen_score:=null; chosen_status:=null; chosen_assigned:=null; chosen_target:=null;
      select c.user_id,c.score,c.availability_status,c.assigned_count,c.requested_target
      into chosen_user,chosen_score,chosen_status,chosen_assigned,chosen_target
      from (
        select t.user_id,t.assigned_count,t.requested_target,e.availability_status,
          optional_weight
          + greatest(t.requested_target-t.assigned_count,0)*fairness_weight*t.employment_factor
          + greatest(t.proportional_target-t.assigned_count,0)*fairness_weight*0.5
          + case when e.availability_status='preferred' then preference_weight else 0 end
          + case when not max_hard and t.requested_max is not null and t.assigned_count>=t.requested_max
              then -fairness_weight*4*(t.assigned_count-t.requested_max+1) else 0 end as score
        from public.dynamic_schedule_shadow_targets t
        join public.dynamic_availability_submissions sub on sub.period_id=period.id and sub.user_id=t.user_id
        join public.dynamic_availability_entries e on e.submission_id=sub.id and e.slot_id=sl.id and e.availability_status in ('preferred','available')
        where t.draft_id=v_draft_id
          and (not max_hard or t.requested_max is null or t.assigned_count<t.requested_max)
          and public.dynamic_shadow_candidate_allowed(v_draft_id,t.user_id,sl.id,max_per_day,no_consecutive,min_rest)
        order by score desc,t.assigned_count asc,t.user_id limit 1
      ) c;
      exit when chosen_user is null;
      insert into public.dynamic_schedule_shadow_assignments(draft_id,slot_id,user_id,assignment_tier,score,reasons)
      values(v_draft_id,sl.id,chosen_user,'target_optional',chosen_score,jsonb_build_array(
        'עובד נוסף עד יעד האיוש למשמרת',
        case when chosen_assigned<coalesce(chosen_target,0) then 'איזון לכיוון היעד החודשי' else 'היעד החודשי הוא העדפה ולא חסם' end,
        case when chosen_status='preferred' then 'מעדיף' else 'זמין' end
      ));
      update public.dynamic_schedule_shadow_targets t set assigned_count=t.assigned_count+1
      where t.draft_id=v_draft_id and t.user_id=chosen_user;
      if chosen_assigned>=coalesce(chosen_target,0) then above_target_assignments:=above_target_assignments+1; end if;
      assigned_optional:=assigned_optional+1;
    end loop;
  end loop;

  update public.dynamic_schedule_shadow_drafts d
  set status=case when unfilled=0 then 'generated' else 'incomplete' end,
      metrics=jsonb_build_object(
        'requiredAssignmentsCreated',assigned_required,'optionalAssignmentsCreated',assigned_optional,
        'unfilledRequiredPositions',unfilled,'avoidAssignments',avoid_assignments,
        'aboveTargetAssignments',above_target_assignments,
        'algorithm','scarcity_first_soft_target_employment_v2_1','wholePeriodScarcity',true,
        'targetIsEligibilityCutoff',false,'employmentScopeIsEligibilityCutoff',false,
        'partTimeRecommendationFactor',0.5
      ),updated_at=now()
  where d.id=v_draft_id;

  return jsonb_build_object(
    'draftId',v_draft_id,'mode','shadow','requiredAssignmentsCreated',assigned_required,
    'optionalAssignmentsCreated',assigned_optional,'unfilledRequiredPositions',unfilled,
    'avoidAssignments',avoid_assignments,'aboveTargetAssignments',above_target_assignments,
    'algorithm','scarcity_first_soft_target_employment_v2_1','wholePeriodScarcity',true,
    'targetIsEligibilityCutoff',false,'employmentScopeIsEligibilityCutoff',false,
    'partTimeRecommendationFactor',0.5,'feasibility',feasibility
  );
end;
$function$;

create or replace function public.create_dynamic_monthly_rotation_draft(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_actor uuid:=auth.uid();
  v_job public.job_types%rowtype;
  v_period public.dynamic_availability_periods%rowtype;
  v_material public.job_type_schedule_materializations%rowtype;
  v_draft_id uuid;
  v_rotation uuid[];
  v_anchor date;
  v_source text;
  v_member_count integer:=0;
  v_rotation_count integer:=0;
  v_slot record;
  v_original uuid;
  v_assigned uuid;
  v_status text;
  v_index integer;
  v_unfilled integer:=0;
  v_substitutions integer:=0;
  v_created integer:=0;
  v_candidate record;
  v_history_rows integer:=0;
begin
  if v_actor is null then raise exception 'not authenticated'; end if;
  if not public.has_dynamic_job_type_permission('rotation.generate', requested_job_type_id, v_actor) then
    raise exception 'not allowed';
  end if;
  if requested_month not between 1 and 12 then raise exception 'invalid month'; end if;

  select * into v_job from public.job_types where id=requested_job_type_id;
  if v_job.id is null then raise exception 'job type not found'; end if;

  select * into v_material
  from public.job_type_schedule_materializations m
  where m.job_type_id=v_job.id and m.effective_month=make_date(requested_year,requested_month,1);

  if coalesce(v_material.scheduling_strategy,v_job.scheduling_strategy,'availability_optimizer') <> 'monthly_rotation_constraints' then
    raise exception 'job type is not configured for monthly rotation';
  end if;
  if coalesce(v_material.work_mode, v_job.scheduling_config#>>'{shiftPattern,workMode}') <> 'on_call_daily' then
    raise exception 'monthly rotation currently requires daily on-call work mode';
  end if;

  select * into v_period from public.dynamic_availability_periods
  where job_type_id=v_job.id and year=requested_year and month=requested_month;
  if v_period.id is null then raise exception 'dynamic availability period not found'; end if;
  if v_period.status <> 'closed' then raise exception 'availability period must be closed before scheduling'; end if;

  select count(*)::integer into v_member_count
  from public.job_type_memberships m join public.profiles p on p.id=m.user_id and p.is_active=true
  where m.job_type_id=v_job.id;
  if v_member_count < 2 then raise exception 'monthly rotation requires at least two active role members'; end if;

  select rotation_user_ids,anchor_date,source into v_rotation,v_anchor,v_source
  from public.dynamic_job_type_rotation_state where job_type_id=v_job.id for update;

  if v_rotation is null then
    -- Build candidate cycles from every historical contiguous N-row window whose
    -- original users are all distinct, then score each candidate against all imported
    -- original assignments. This is done once and persisted.
    with hist as (
      select ha.work_date,coalesce(ha.original_user_id,ha.assigned_user_id) user_id,
             row_number() over(order by ha.work_date,ha.id) rn
      from public.dynamic_historical_assignments ha
      join public.dynamic_historical_periods hp on hp.id=ha.historical_period_id
      join public.job_type_memberships jm on jm.job_type_id=hp.job_type_id and jm.user_id=coalesce(ha.original_user_id,ha.assigned_user_id)
      where hp.job_type_id=v_job.id and ha.work_date is not null and coalesce(ha.original_user_id,ha.assigned_user_id) is not null
    ), candidates as (
      select h0.work_date anchor_date,
             array_agg(h.user_id order by h.rn) rotation
      from hist h0 join hist h on h.rn between h0.rn and h0.rn+v_member_count-1
      group by h0.rn,h0.work_date
      having count(*)=v_member_count and count(distinct h.user_id)=v_member_count
    ), scored as (
      select c.anchor_date,c.rotation,
             count(*) filter(where h.user_id=c.rotation[((h.work_date-c.anchor_date)%v_member_count+v_member_count)%v_member_count+1])::integer matches,
             count(*)::integer compared
      from candidates c cross join hist h
      group by c.anchor_date,c.rotation
      order by matches desc,compared desc,c.anchor_date desc
      limit 1
    )
    select rotation,anchor_date,'historical_best_window',compared
      into v_rotation,v_anchor,v_source,v_history_rows from scored;

    if v_rotation is null or cardinality(v_rotation)<>v_member_count then
      select array_agg(x.user_id order by x.display_name,x.user_id),make_date(requested_year,requested_month,1),'membership_fallback'
      into v_rotation,v_anchor,v_source
      from (
        select m.user_id,coalesce(p.schedule_name,p.display_name,p.email,m.user_id::text) display_name
        from public.job_type_memberships m join public.profiles p on p.id=m.user_id and p.is_active=true
        where m.job_type_id=v_job.id
      ) x;
    end if;

    insert into public.dynamic_job_type_rotation_state(job_type_id,rotation_user_ids,anchor_date,source,source_metadata,created_by)
    values(v_job.id,v_rotation,v_anchor,v_source,jsonb_build_object('historicalRowsCompared',v_history_rows,'memberCount',v_member_count),v_actor);
  end if;

  v_rotation_count:=cardinality(v_rotation);
  if v_rotation_count<>v_member_count then
    raise exception 'saved rotation has % members but role currently has % active members; rotation membership changes require an explicit rotation update',v_rotation_count,v_member_count;
  end if;

  insert into public.dynamic_schedule_shadow_drafts(job_type_id,availability_period_id,year,month,status,feasibility_snapshot,rules_snapshot,metrics,created_by)
  values(v_job.id,v_period.id,requested_year,requested_month,'shadow','{}'::jsonb,
    jsonb_build_object('strategy','monthly_rotation_constraints','rotationUserIds',to_jsonb(v_rotation),'anchorDate',v_anchor,'rotationSource',v_source),
    '{}'::jsonb,v_actor) returning id into v_draft_id;

  for v_slot in
    select s.* from public.dynamic_availability_slots s where s.period_id=v_period.id order by s.shift_date,s.start_time,s.id
  loop
    v_index:=((v_slot.shift_date-v_anchor)%v_rotation_count+v_rotation_count)%v_rotation_count+1;
    v_original:=v_rotation[v_index];
    v_assigned:=null;

    select e.availability_status into v_status
    from public.dynamic_availability_submissions sub
    join public.dynamic_availability_entries e on e.submission_id=sub.id and e.slot_id=v_slot.id
    where sub.period_id=v_period.id and sub.user_id=v_original
    order by case when sub.status='submitted' then 0 else 1 end,sub.updated_at desc limit 1;

    if coalesce(v_status,'available') <> 'unavailable' then
      v_assigned:=v_original;
    else
      select c.* into v_candidate from (
        select m.user_id,e.availability_status,
          (select count(*) from public.dynamic_schedule_shadow_assignments a where a.draft_id=v_draft_id and a.user_id=m.user_id)::integer month_count,
          exists(
            select 1 from public.dynamic_schedule_shadow_assignments pa
            join public.dynamic_availability_slots ps on ps.id=pa.slot_id
            where pa.draft_id=v_draft_id and pa.user_id=m.user_id and ps.shift_date=v_slot.shift_date-1
          ) worked_previous_day
        from public.job_type_memberships m
        join public.profiles p on p.id=m.user_id and p.is_active=true
        left join public.dynamic_availability_submissions sub on sub.period_id=v_period.id and sub.user_id=m.user_id
        left join public.dynamic_availability_entries e on e.submission_id=sub.id and e.slot_id=v_slot.id
        where m.job_type_id=v_job.id and m.user_id<>v_original and coalesce(e.availability_status,'available')<>'unavailable'
      ) c
      order by c.worked_previous_day asc,
        case c.availability_status when 'preferred' then 0 when 'available' then 1 when null then 2 when 'avoid' then 3 else 2 end,
        c.month_count asc,c.user_id
      limit 1;
      v_assigned:=v_candidate.user_id;
      if v_assigned is not null then v_substitutions:=v_substitutions+1; end if;
    end if;

    if v_assigned is null then
      v_unfilled:=v_unfilled+greatest(v_slot.min_workers,1);
    else
      insert into public.dynamic_schedule_shadow_assignments(
        draft_id,slot_id,user_id,original_user_id,engine_user_id,assignment_tier,score,reasons
      ) values(
        v_draft_id,v_slot.id,v_assigned,v_original,v_assigned,'required',0,
        jsonb_build_array(
          'סבב חודשי קבוע',
          case when v_assigned=v_original then 'העובד המקורי ברוטציה' else 'מחליף עקב אילוץ של העובד המקורי' end
        )
      );
      v_created:=v_created+1;
    end if;
  end loop;

  update public.dynamic_schedule_shadow_drafts
  set status=case when v_unfilled=0 then 'generated' else 'incomplete' end,
      metrics=jsonb_build_object(
        'requiredAssignmentsCreated',v_created,'optionalAssignmentsCreated',0,
        'unfilledRequiredPositions',v_unfilled,'effectiveUnfilledRequiredPositions',v_unfilled,
        'rotationSubstitutions',v_substitutions,'algorithm','persistent_daily_rotation_v1',
        'rotationUserIds',to_jsonb(v_rotation),'rotationAnchorDate',v_anchor,'rotationSource',v_source,
        'originalRotationPreserved',true
      ),updated_at=now()
  where id=v_draft_id;

  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,metadata)
  values('system_event',v_actor,'dynamic_schedule_draft',v_draft_id,'טיוטת סבב חודשי דינמי נוצרה',
    jsonb_build_object('job_type_id',v_job.id,'year',requested_year,'month',requested_month,'rotation_source',v_source,'substitutions',v_substitutions,'unfilled',v_unfilled));

  return jsonb_build_object(
    'draftId',v_draft_id,'mode','monthly_rotation','requiredAssignmentsCreated',v_created,
    'optionalAssignmentsCreated',0,'unfilledRequiredPositions',v_unfilled,
    'algorithm','persistent_daily_rotation_v1','rotationUserIds',to_jsonb(v_rotation),
    'rotationAnchorDate',v_anchor,'rotationSource',v_source,'rotationSubstitutions',v_substitutions,
    'originalRotationPreserved',true
  );
end;$function$;

create or replace function public.get_dynamic_schedule_draft_editor(requested_draft_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid := auth.uid();
  d public.dynamic_schedule_shadow_drafts%rowtype;
  j public.job_types%rowtype;
  p public.dynamic_availability_periods%rowtype;
  v_metrics jsonb;
begin
  if v_user is null then raise exception 'not authenticated'; end if;

  select * into d from public.dynamic_schedule_shadow_drafts where id=requested_draft_id;
  if not public.has_dynamic_job_type_permission('schedule.view_team', d.job_type_id, v_user) then raise exception 'not allowed'; end if;
  if d.id is null then raise exception 'draft not found'; end if;
  select * into j from public.job_types where id=d.job_type_id;
  select * into p from public.dynamic_availability_periods where id=d.availability_period_id;
  v_metrics := public.dynamic_refresh_draft_metrics(d.id);

  return jsonb_build_object(
    'draftId',d.id,'jobTypeId',d.job_type_id,'jobTypeName',j.name,
    'year',d.year,'month',d.month,'status',(select status from public.dynamic_schedule_shadow_drafts where id=d.id),
    'metrics',v_metrics,
    'slots',coalesce((
      select jsonb_agg(jsonb_build_object(
        'slotId',sl.id,'date',sl.shift_date,'shiftCode',sl.shift_code,'shiftName',sl.shift_name,
        'startTime',sl.start_time,'endTime',sl.end_time,
        'minWorkers',sl.min_workers,'targetWorkers',sl.target_workers,'maxWorkers',sl.max_workers,
        'intentionallyUnassignedCount',least(coalesce(o.intentionally_unassigned_count,0),greatest(sl.min_workers-coalesce(ac.required_count,0),0)),
        'overrideNote',o.note,
        'assignments',coalesce((
          select jsonb_agg(jsonb_build_object(
            'id',a.id,'userId',a.user_id,'displayName',ap.display_name,
            'engineUserId',a.engine_user_id,'engineDisplayName',ep.display_name,
            'tier',a.assignment_tier,'score',a.score,'reasons',a.reasons,
            'managerEdited',a.manager_edited_at is not null or (a.engine_user_id is not null and a.engine_user_id<>a.user_id),
            'managerOverrideNote',a.manager_override_note
          ) order by case when a.assignment_tier='required' then 0 else 1 end, ap.display_name)
          from public.dynamic_schedule_shadow_assignments a
          join public.profiles ap on ap.id=a.user_id
          left join public.profiles ep on ep.id=a.engine_user_id
          where a.draft_id=d.id and a.slot_id=sl.id
        ),'[]'::jsonb),
        'candidates',coalesce((
          select jsonb_agg(jsonb_build_object(
            'userId',m.user_id,'displayName',mp.display_name,
            'availabilityStatus',e.availability_status,
            'assignedCount',(select count(*) from public.dynamic_schedule_shadow_assignments xa where xa.draft_id=d.id and xa.user_id=m.user_id),
            'maximum',t.requested_max,
            'isAssignedHere',exists(select 1 from public.dynamic_schedule_shadow_assignments xa where xa.draft_id=d.id and xa.slot_id=sl.id and xa.user_id=m.user_id)
          ) order by
            case e.availability_status when 'preferred' then 0 when 'available' then 1 when 'avoid' then 2 when 'unavailable' then 3 else 4 end,
            mp.display_name)
          from public.job_type_memberships m
          join public.profiles mp on mp.id=m.user_id and mp.is_active=true
          left join public.dynamic_availability_submissions sub on sub.period_id=p.id and sub.user_id=m.user_id
          left join public.dynamic_availability_entries e on e.submission_id=sub.id and e.slot_id=sl.id
          left join public.dynamic_schedule_shadow_targets t on t.draft_id=d.id and t.user_id=m.user_id
          where m.job_type_id=d.job_type_id
        ),'[]'::jsonb)
      ) order by sl.shift_date,sl.start_time,sl.shift_name)
      from public.dynamic_availability_slots sl
      left join (
        select slot_id,count(*) filter(where assignment_tier='required')::integer required_count
        from public.dynamic_schedule_shadow_assignments where draft_id=d.id group by slot_id
      ) ac on ac.slot_id=sl.id
      left join public.dynamic_schedule_draft_slot_overrides o on o.draft_id=d.id and o.slot_id=sl.id
      where sl.period_id=p.id
    ),'[]'::jsonb)
  );
end;
$function$;

create or replace function public.set_dynamic_schedule_draft_assignment(
  requested_draft_id uuid,
  requested_slot_id uuid,
  requested_assignment_id uuid,
  requested_user_id uuid,
  requested_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid := auth.uid();
  d public.dynamic_schedule_shadow_drafts%rowtype;
  sl public.dynamic_availability_slots%rowtype;
  a public.dynamic_schedule_shadow_assignments%rowtype;
  v_assignment_id uuid;
  v_tier text := 'required';
  v_count integer;
begin
  if v_user is null then raise exception 'not authenticated'; end if;

  select * into d from public.dynamic_schedule_shadow_drafts where id=requested_draft_id;
  if not public.has_dynamic_job_type_permission('schedule.edit_draft', d.job_type_id, v_user) then raise exception 'not allowed'; end if;
  if d.id is null then raise exception 'draft not found'; end if;
  if d.status not in ('generated','incomplete') then raise exception 'draft is not editable'; end if;
  select * into sl from public.dynamic_availability_slots where id=requested_slot_id and period_id=d.availability_period_id;
  if sl.id is null then raise exception 'slot not found'; end if;
  if not exists(
    select 1 from public.job_type_memberships m join public.profiles p on p.id=m.user_id
    where m.job_type_id=d.job_type_id and m.user_id=requested_user_id and p.is_active=true
  ) then raise exception 'user is not an active member of this role'; end if;

  if requested_assignment_id is not null then
    select * into a from public.dynamic_schedule_shadow_assignments
    where id=requested_assignment_id and draft_id=d.id and slot_id=sl.id;
    if a.id is null then raise exception 'assignment not found'; end if;
    if exists(select 1 from public.dynamic_schedule_shadow_assignments x where x.draft_id=d.id and x.slot_id=sl.id and x.user_id=requested_user_id and x.id<>a.id) then
      raise exception 'user is already assigned to this shift';
    end if;
    update public.dynamic_schedule_shadow_assignments
    set engine_user_id=coalesce(engine_user_id,user_id), user_id=requested_user_id,
        manager_edited_by=v_user,manager_edited_at=now(),manager_override_note=nullif(btrim(requested_note),'')
    where id=a.id
    returning id into v_assignment_id;
  else
    if exists(select 1 from public.dynamic_schedule_shadow_assignments x where x.draft_id=d.id and x.slot_id=sl.id and x.user_id=requested_user_id) then
      raise exception 'user is already assigned to this shift';
    end if;
    select count(*)::integer into v_count from public.dynamic_schedule_shadow_assignments x where x.draft_id=d.id and x.slot_id=sl.id;
    if v_count>=sl.max_workers then raise exception 'shift reached maximum workers'; end if;
    v_tier := case when v_count<sl.min_workers then 'required' else 'target_optional' end;
    insert into public.dynamic_schedule_shadow_assignments(
      draft_id,slot_id,user_id,engine_user_id,assignment_tier,score,reasons,manager_edited_by,manager_edited_at,manager_override_note
    ) values(
      d.id,sl.id,requested_user_id,null,v_tier,0,jsonb_build_array('נוסף ידנית על ידי מנהל'),v_user,now(),nullif(btrim(requested_note),'')
    ) returning id into v_assignment_id;
  end if;

  perform public.dynamic_refresh_draft_metrics(d.id);
  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,metadata)
  values('system_event',v_user,'dynamic_schedule_draft',d.id,'שיבוץ בטיוטה הדינמית נערך ידנית',
    jsonb_build_object('draft_id',d.id,'slot_id',sl.id,'assignment_id',v_assignment_id,'user_id',requested_user_id));
  return jsonb_build_object('saved',true,'assignmentId',v_assignment_id);
end;
$function$;

create or replace function public.remove_dynamic_schedule_draft_assignment(
  requested_draft_id uuid,
  requested_assignment_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid:=auth.uid();
  d public.dynamic_schedule_shadow_drafts%rowtype;
  a public.dynamic_schedule_shadow_assignments%rowtype;
begin
  if v_user is null then raise exception 'not authenticated'; end if;
  select * into d from public.dynamic_schedule_shadow_drafts where id=requested_draft_id;
  if not public.has_dynamic_job_type_permission('schedule.edit_draft', d.job_type_id, v_user) then raise exception 'not allowed'; end if;
  if d.id is null or d.status not in ('generated','incomplete') then raise exception 'draft is not editable'; end if;
  select * into a from public.dynamic_schedule_shadow_assignments where id=requested_assignment_id and draft_id=d.id;
  if a.id is null then raise exception 'assignment not found'; end if;
  delete from public.dynamic_schedule_shadow_assignments where id=a.id;
  perform public.dynamic_refresh_draft_metrics(d.id);
  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,metadata)
  values('system_event',v_user,'dynamic_schedule_draft',d.id,'שיבוץ הוסר מטיוטה דינמית',
    jsonb_build_object('draft_id',d.id,'slot_id',a.slot_id,'assignment_id',a.id,'user_id',a.user_id));
  return jsonb_build_object('removed',true,'assignmentId',a.id,'slotId',a.slot_id);
end;
$function$;

create or replace function public.set_dynamic_schedule_slot_intentionally_unassigned(
  requested_draft_id uuid,
  requested_slot_id uuid,
  requested_count integer,
  requested_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid:=auth.uid();
  d public.dynamic_schedule_shadow_drafts%rowtype;
  sl public.dynamic_availability_slots%rowtype;
  v_assigned integer;
  v_missing integer;
  v_count integer;
begin
  if v_user is null then raise exception 'not authenticated'; end if;
  select * into d from public.dynamic_schedule_shadow_drafts where id=requested_draft_id;
  if not public.has_dynamic_job_type_permission('schedule.edit_draft', d.job_type_id, v_user) then raise exception 'not allowed'; end if;
  if d.id is null or d.status not in ('generated','incomplete') then raise exception 'draft is not editable'; end if;
  select * into sl from public.dynamic_availability_slots where id=requested_slot_id and period_id=d.availability_period_id;
  if sl.id is null then raise exception 'slot not found'; end if;
  select count(*)::integer into v_assigned from public.dynamic_schedule_shadow_assignments where draft_id=d.id and slot_id=sl.id and assignment_tier='required';
  v_missing:=greatest(sl.min_workers-v_assigned,0);
  v_count:=greatest(least(coalesce(requested_count,0),v_missing),0);

  if v_count=0 then
    delete from public.dynamic_schedule_draft_slot_overrides where draft_id=d.id and slot_id=sl.id;
  else
    insert into public.dynamic_schedule_draft_slot_overrides(draft_id,slot_id,intentionally_unassigned_count,note,updated_by,updated_at)
    values(d.id,sl.id,v_count,nullif(btrim(requested_note),''),v_user,now())
    on conflict(draft_id,slot_id) do update set
      intentionally_unassigned_count=excluded.intentionally_unassigned_count,note=excluded.note,updated_by=excluded.updated_by,updated_at=now();
  end if;
  perform public.dynamic_refresh_draft_metrics(d.id);
  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,metadata)
  values('system_event',v_user,'dynamic_schedule_draft',d.id,
    case when v_count>0 then 'חוסר בטיוטה סומן כלא מאויש בכוונה' else 'סימון לא מאויש בכוונה הוסר' end,
    jsonb_build_object('draft_id',d.id,'slot_id',sl.id,'intentionally_unassigned_count',v_count));
  return jsonb_build_object('saved',true,'slotId',sl.id,'intentionallyUnassignedCount',v_count);
end;
$function$;

create or replace function public.publish_dynamic_schedule_draft(requested_draft_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid:=auth.uid();
  target_draft public.dynamic_schedule_shadow_drafts%rowtype;
  target_job public.job_types%rowtype;
  target_period public.dynamic_availability_periods%rowtype;
  v_publication_id uuid;
  inserted_assignments integer:=0;
  v_metrics jsonb;
  v_unfilled integer:=0;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;

  select * into target_draft from public.dynamic_schedule_shadow_drafts where id=requested_draft_id;
  if not public.has_dynamic_job_type_permission('schedule.publish', target_draft.job_type_id, current_user_id) then raise exception 'not allowed'; end if;
  if target_draft.id is null then raise exception 'draft not found'; end if;
  select * into target_job from public.job_types where id=target_draft.job_type_id;
  select * into target_period from public.dynamic_availability_periods where id=target_draft.availability_period_id;
  if target_period.status <> 'closed' then raise exception 'availability period must be closed before publishing'; end if;
  if target_draft.status not in ('generated','incomplete') then raise exception 'draft is not ready for publishing'; end if;

  v_metrics:=public.dynamic_refresh_draft_metrics(target_draft.id);
  v_unfilled:=coalesce((v_metrics->>'effectiveUnfilledRequiredPositions')::integer,0);
  if v_unfilled>0 then raise exception 'draft has % unfilled required positions that were not intentionally left empty',v_unfilled; end if;

  insert into public.dynamic_schedule_publications(
    job_type_id,availability_period_id,draft_id,year,month,status,config_snapshot,published_by,published_at,updated_at
  ) values(
    target_draft.job_type_id,target_draft.availability_period_id,target_draft.id,target_draft.year,target_draft.month,'published',
    jsonb_build_object('jobType',target_job.scheduling_config,'draftMetrics',v_metrics),current_user_id,now(),now()
  ) on conflict(job_type_id,year,month) do update set
    availability_period_id=excluded.availability_period_id,draft_id=excluded.draft_id,status='published',
    config_snapshot=excluded.config_snapshot,published_by=excluded.published_by,published_at=now(),updated_at=now()
  returning id into v_publication_id;

  delete from public.dynamic_schedule_published_assignments where publication_id=v_publication_id;
  delete from public.dynamic_schedule_published_unassigned where publication_id=v_publication_id;

  insert into public.dynamic_schedule_published_assignments(
    publication_id,source_assignment_id,slot_id,shift_date,shift_code,shift_name,start_time,end_time,user_id,
    assignment_tier,score,reasons,engine_user_id,manager_edited,manager_override_note
  )
  select v_publication_id,a.id,s.id,s.shift_date,s.shift_code,s.shift_name,s.start_time,s.end_time,a.user_id,
         a.assignment_tier,a.score,a.reasons,a.engine_user_id,
         (a.manager_edited_at is not null or (a.engine_user_id is not null and a.engine_user_id<>a.user_id)),a.manager_override_note
  from public.dynamic_schedule_shadow_assignments a
  join public.dynamic_availability_slots s on s.id=a.slot_id
  where a.draft_id=target_draft.id;
  get diagnostics inserted_assignments = row_count;

  insert into public.dynamic_schedule_published_unassigned(
    publication_id,slot_id,shift_date,shift_code,shift_name,intentionally_unassigned_count,note
  )
  select v_publication_id,sl.id,sl.shift_date,sl.shift_code,sl.shift_name,
         least(o.intentionally_unassigned_count,greatest(sl.min_workers-coalesce(a.cnt,0),0)),o.note
  from public.dynamic_schedule_draft_slot_overrides o
  join public.dynamic_availability_slots sl on sl.id=o.slot_id
  left join (
    select slot_id,count(*) filter(where assignment_tier='required')::integer cnt
    from public.dynamic_schedule_shadow_assignments where draft_id=target_draft.id group by slot_id
  ) a on a.slot_id=sl.id
  where o.draft_id=target_draft.id
    and least(o.intentionally_unassigned_count,greatest(sl.min_workers-coalesce(a.cnt,0),0))>0;

  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,metadata)
  values('system_event',current_user_id,'dynamic_schedule_publication',v_publication_id,'לוח דינמי פורסם',
    jsonb_build_object('draft_id',target_draft.id,'job_type_id',target_draft.job_type_id,'year',target_draft.year,'month',target_draft.month,'assignment_count',inserted_assignments));

  return jsonb_build_object('publicationId',v_publication_id,'published',true,'assignmentCount',inserted_assignments);
end;
$function$;

create or replace function public.get_dynamic_published_schedule_editor(
  requested_publication_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_actor uuid := auth.uid();
  v_publication public.dynamic_schedule_publications%rowtype;
  v_job public.job_types%rowtype;
  v_current_month date := date_trunc('month', (now() at time zone 'Asia/Jerusalem')::date)::date;
  v_publication_month date;
  v_editable boolean := false;
  v_reason text := null;
  v_members jsonb := '[]'::jsonb;
  v_slots jsonb := '[]'::jsonb;
begin
  if v_actor is null then raise exception 'not authenticated'; end if;

  select * into v_publication
  from public.dynamic_schedule_publications
  where id=requested_publication_id;
  if v_publication.id is null then raise exception 'publication not found'; end if;
  if not public.has_dynamic_job_type_permission('schedule.view_team', v_publication.job_type_id, v_actor) then raise exception 'not allowed'; end if;

  select * into v_job from public.job_types where id=v_publication.job_type_id;
  if v_job.id is null then raise exception 'job type not found'; end if;

  v_publication_month := make_date(v_publication.year,v_publication.month,1);
  if v_publication.status <> 'published' then
    v_reason := 'לוח זה אינו פתוח לעריכה משום שהוא בארכיון.';
  elsif v_publication_month = v_current_month
     or v_publication_month = (v_current_month + interval '1 month')::date then
    v_editable := true;
  elsif v_publication_month < v_current_month then
    v_reason := 'לוח היסטורי נשמר לקריאה בלבד.';
  else
    v_reason := 'ניתן לערוך לוח מפורסם רק בחודש הנוכחי או בחודש הבא.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object('userId',m.user_id,'displayName',p.display_name)
    order by p.display_name
  ),'[]'::jsonb)
  into v_members
  from public.job_type_memberships m
  join public.profiles p on p.id=m.user_id
  where m.job_type_id=v_publication.job_type_id
    and p.is_active=true;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'slotId',sl.id,
      'shiftDate',sl.shift_date,
      'shiftCode',sl.shift_code,
      'shiftName',sl.shift_name,
      'startTime',sl.start_time,
      'endTime',sl.end_time,
      'intentionallyUnassignedCount',coalesce(pu.intentionally_unassigned_count,0),
      'assignments',coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id',a.id,
            'userId',a.user_id,
            'displayName',p.display_name,
            'userIsActive',coalesce(p.is_active,false),
            'originalUserId',a.original_user_id,
            'originalDisplayName',op.display_name,
            'managerEdited',a.manager_edited,
            'managerOverrideNote',a.manager_override_note
          ) order by p.display_name
        )
        from public.dynamic_schedule_published_assignments a
        left join public.profiles p on p.id=a.user_id
        left join public.profiles op on op.id=a.original_user_id
        where a.publication_id=v_publication.id and a.slot_id=sl.id
      ),'[]'::jsonb)
    ) order by sl.shift_date,sl.start_time,sl.shift_name
  ),'[]'::jsonb)
  into v_slots
  from public.dynamic_availability_slots sl
  left join public.dynamic_schedule_published_unassigned pu
    on pu.publication_id=v_publication.id and pu.slot_id=sl.id
  where sl.period_id=v_publication.availability_period_id;

  return jsonb_build_object(
    'publicationId',v_publication.id,
    'jobTypeId',v_job.id,
    'jobTypeName',v_job.name,
    'year',v_publication.year,
    'month',v_publication.month,
    'editable',v_editable,
    'editabilityReason',v_reason,
    'members',v_members,
    'slots',v_slots
  );
end;
$function$;

create or replace function public.set_dynamic_published_schedule_assignment(
  requested_publication_id uuid,
  requested_slot_id uuid,
  requested_assignment_id uuid default null,
  requested_user_id uuid default null,
  requested_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_actor uuid := auth.uid();
  v_publication public.dynamic_schedule_publications%rowtype;
  v_slot public.dynamic_availability_slots%rowtype;
  v_assignment public.dynamic_schedule_published_assignments%rowtype;
  v_unassigned public.dynamic_schedule_published_unassigned%rowtype;
  v_current_month date := date_trunc('month', (now() at time zone 'Asia/Jerusalem')::date)::date;
  v_publication_month date;
  v_required_assigned integer := 0;
  v_missing integer := 0;
  v_original_user_id uuid;
  v_new_assignment_id uuid;
begin
  if v_actor is null then raise exception 'not authenticated'; end if;

  select * into v_publication
  from public.dynamic_schedule_publications
  where id=requested_publication_id
  for update;
  if v_publication.id is null then raise exception 'publication not found'; end if;
  if not public.has_dynamic_job_type_permission('schedule.edit_published', v_publication.job_type_id, v_actor) then raise exception 'not allowed'; end if;
  if v_publication.status <> 'published' then raise exception 'published schedule is not editable'; end if;

  v_publication_month := make_date(v_publication.year,v_publication.month,1);
  if v_publication_month not in (v_current_month,(v_current_month+interval '1 month')::date) then
    raise exception 'only current month or next published month can be edited';
  end if;

  select * into v_slot
  from public.dynamic_availability_slots
  where id=requested_slot_id and period_id=v_publication.availability_period_id;
  if v_slot.id is null then raise exception 'slot not found in this publication'; end if;

  if requested_user_id is not null and not exists (
    select 1
    from public.job_type_memberships m
    join public.profiles p on p.id=m.user_id
    where m.job_type_id=v_publication.job_type_id
      and m.user_id=requested_user_id
      and p.is_active=true
  ) then
    raise exception 'requested user is not an active member of this role';
  end if;

  if requested_assignment_id is not null then
    select * into v_assignment
    from public.dynamic_schedule_published_assignments
    where id=requested_assignment_id
      and publication_id=v_publication.id
      and slot_id=v_slot.id
    for update;
    if v_assignment.id is null then raise exception 'assignment not found'; end if;

    if requested_user_id is null then
      v_original_user_id := coalesce(v_assignment.original_user_id,v_assignment.engine_user_id,v_assignment.user_id);

      delete from public.dynamic_schedule_published_assignments
      where id=v_assignment.id;

      if v_assignment.assignment_tier='required' then
        select count(*)::integer into v_required_assigned
        from public.dynamic_schedule_published_assignments a
        where a.publication_id=v_publication.id
          and a.slot_id=v_slot.id
          and a.assignment_tier='required';

        v_missing := greatest(v_slot.min_workers-v_required_assigned,0);
        if v_missing>0 then
          insert into public.dynamic_schedule_published_unassigned(
            publication_id,slot_id,shift_date,shift_code,shift_name,
            intentionally_unassigned_count,note,original_user_id
          ) values(
            v_publication.id,v_slot.id,v_slot.shift_date,v_slot.shift_code,v_slot.shift_name,
            v_missing,nullif(trim(coalesce(requested_reason,'')),''),v_original_user_id
          )
          on conflict(publication_id,shift_date,shift_code) do update set
            slot_id=excluded.slot_id,
            intentionally_unassigned_count=excluded.intentionally_unassigned_count,
            note=excluded.note,
            original_user_id=coalesce(public.dynamic_schedule_published_unassigned.original_user_id,excluded.original_user_id);
        else
          delete from public.dynamic_schedule_published_unassigned
          where publication_id=v_publication.id and slot_id=v_slot.id;
        end if;
      end if;

      insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,old_values,new_values,metadata)
      values(
        'system_event',v_actor,'dynamic_schedule_publication',v_publication.id,
        'משמרת בלוח דינמי סומנה כלא מאוישת',
        jsonb_build_object('assignment_id',v_assignment.id,'user_id',v_assignment.user_id),
        jsonb_build_object('intentionally_unassigned',true),
        jsonb_build_object('job_type_id',v_publication.job_type_id,'slot_id',v_slot.id,'shift_date',v_slot.shift_date,'shift_code',v_slot.shift_code,'reason',nullif(trim(coalesce(requested_reason,'')),''))
      );

      update public.dynamic_schedule_publications set updated_at=now() where id=v_publication.id;
      return jsonb_build_object('saved',true,'action','unassigned','publicationId',v_publication.id,'slotId',v_slot.id);
    end if;

    if v_assignment.user_id=requested_user_id then
      return jsonb_build_object('saved',true,'changed',false,'assignmentId',v_assignment.id);
    end if;

    if exists (
      select 1 from public.dynamic_schedule_published_assignments a
      where a.publication_id=v_publication.id and a.slot_id=v_slot.id
        and a.user_id=requested_user_id and a.id<>v_assignment.id
    ) then raise exception 'requested user is already assigned to this shift'; end if;

    update public.dynamic_schedule_published_assignments
    set user_id=requested_user_id,
        manager_edited=true,
        manager_override_note=nullif(trim(coalesce(requested_reason,'')),''),
        user_edited_by=null,
        user_edited_at=null
    where id=v_assignment.id;

    insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,old_values,new_values,metadata)
    values(
      'system_event',v_actor,'dynamic_schedule_publication',v_publication.id,
      'שיבוץ בלוח דינמי שונה על ידי מנהל',
      jsonb_build_object('assignment_id',v_assignment.id,'user_id',v_assignment.user_id),
      jsonb_build_object('assignment_id',v_assignment.id,'user_id',requested_user_id),
      jsonb_build_object('job_type_id',v_publication.job_type_id,'slot_id',v_slot.id,'shift_date',v_slot.shift_date,'shift_code',v_slot.shift_code,'reason',nullif(trim(coalesce(requested_reason,'')),''))
    );

    update public.dynamic_schedule_publications set updated_at=now() where id=v_publication.id;
    return jsonb_build_object('saved',true,'action','reassigned','assignmentId',v_assignment.id,'oldUserId',v_assignment.user_id,'newUserId',requested_user_id);
  end if;

  if requested_user_id is null then raise exception 'requested user is required when filling an unassigned position'; end if;

  select * into v_unassigned
  from public.dynamic_schedule_published_unassigned
  where publication_id=v_publication.id and slot_id=v_slot.id
  for update;
  if v_unassigned.publication_id is null or v_unassigned.intentionally_unassigned_count<1 then
    raise exception 'there is no intentionally unassigned position in this slot';
  end if;

  if exists (
    select 1 from public.dynamic_schedule_published_assignments a
    where a.publication_id=v_publication.id and a.slot_id=v_slot.id and a.user_id=requested_user_id
  ) then raise exception 'requested user is already assigned to this shift'; end if;

  insert into public.dynamic_schedule_published_assignments(
    publication_id,source_assignment_id,slot_id,shift_date,shift_code,shift_name,start_time,end_time,
    user_id,assignment_tier,score,reasons,engine_user_id,manager_edited,manager_override_note,original_user_id
  ) values(
    v_publication.id,null,v_slot.id,v_slot.shift_date,v_slot.shift_code,v_slot.shift_name,v_slot.start_time,v_slot.end_time,
    requested_user_id,'required',0,jsonb_build_array(jsonb_build_object('source','manager_published_edit')),
    v_unassigned.original_user_id,true,nullif(trim(coalesce(requested_reason,'')),''),v_unassigned.original_user_id
  ) returning id into v_new_assignment_id;

  if v_unassigned.intentionally_unassigned_count<=1 then
    delete from public.dynamic_schedule_published_unassigned
    where publication_id=v_publication.id and slot_id=v_slot.id;
  else
    update public.dynamic_schedule_published_unassigned
    set intentionally_unassigned_count=intentionally_unassigned_count-1,
        note=nullif(trim(coalesce(requested_reason,'')),'')
    where publication_id=v_publication.id and slot_id=v_slot.id;
  end if;

  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,new_values,metadata)
  values(
    'system_event',v_actor,'dynamic_schedule_publication',v_publication.id,
    'עמדה לא מאוישת בלוח דינמי אוישה על ידי מנהל',
    jsonb_build_object('assignment_id',v_new_assignment_id,'user_id',requested_user_id),
    jsonb_build_object('job_type_id',v_publication.job_type_id,'slot_id',v_slot.id,'shift_date',v_slot.shift_date,'shift_code',v_slot.shift_code,'reason',nullif(trim(coalesce(requested_reason,'')),''))
  );

  update public.dynamic_schedule_publications set updated_at=now() where id=v_publication.id;
  return jsonb_build_object('saved',true,'action','filled','assignmentId',v_new_assignment_id,'newUserId',requested_user_id);
end;
$function$;

create or replace function public.get_dynamic_availability_shadow_workspace(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid := auth.uid();
  job public.job_types%rowtype;
  period public.dynamic_availability_periods%rowtype;
  normalized_config jsonb;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;
  if not public.has_dynamic_job_type_permission('availability.view_team', requested_job_type_id, current_user_id) then raise exception 'not allowed'; end if;
  select * into job from public.job_types where id=requested_job_type_id;
  if job.id is null then raise exception 'job type not found'; end if;
  select * into period from public.dynamic_availability_periods where job_type_id=job.id and year=requested_year and month=requested_month;

  normalized_config := jsonb_build_object(
    'enabled', coalesce((job.availability_config->>'enabled')::boolean,true),
    'statuses', case when jsonb_typeof(job.availability_config->'statuses')='array' and jsonb_array_length(job.availability_config->'statuses')>0 then job.availability_config->'statuses' else '["available","unavailable"]'::jsonb end,
    'allowNotes', coalesce((job.availability_config->>'allowNotes')::boolean,true),
    'monthlyCapacity', coalesce(job.availability_config->'monthlyCapacity','{"enabled":false,"minEnabled":false,"targetEnabled":false,"maxEnabled":false,"defaultMin":null,"defaultTarget":null,"defaultMax":null}'::jsonb),
    'limits', coalesce(job.availability_config->'limits','{"maxNightsEnabled":false,"defaultMaxNights":null,"maxWeekendsEnabled":false,"defaultMaxWeekends":null,"maxHolidaysEnabled":false,"defaultMaxHolidays":null}'::jsonb)
  );

  return jsonb_build_object(
    'materialized', period.id is not null,'mode','shadow','periodId',period.id,'jobTypeId',job.id,'jobTypeName',job.name,
    'availabilityConfig',normalized_config,
    'slots',case when period.id is null then '[]'::jsonb else coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'date',s.shift_date,'shiftCode',s.shift_code,'shiftName',s.shift_name,'startTime',s.start_time,'endTime',s.end_time,'holidayName',s.holiday_name,'sourceDayKind',s.source_day_kind,'effectiveDayKind',s.effective_day_kind,'minWorkers',s.min_workers,'targetWorkers',s.target_workers,'maxWorkers',s.max_workers) order by s.shift_date,s.start_time,s.shift_code) from public.dynamic_availability_slots s where s.period_id=period.id),'[]'::jsonb) end,
    'members',coalesce((select jsonb_agg(jsonb_build_object('userId',m.user_id,'displayName',p.display_name,'isActive',p.is_active,'submissionId',sub.id,'status',coalesce(sub.status,'draft'),'minimum',sub.min_shifts,'target',sub.target_shifts,'maximum',sub.max_shifts,'maxNights',sub.max_nights,'maxWeekends',sub.max_weekends,'maxHolidays',sub.max_holidays,'note',sub.note,'entries',coalesce((select jsonb_object_agg(e.slot_id::text,jsonb_build_object('status',e.availability_status,'note',e.note)) from public.dynamic_availability_entries e where e.submission_id=sub.id),'{}'::jsonb)) order by p.is_active desc,p.display_name) from public.job_type_memberships m join public.profiles p on p.id=m.user_id left join public.dynamic_availability_submissions sub on sub.period_id=period.id and sub.user_id=m.user_id where m.job_type_id=job.id),'[]'::jsonb)
  );
end;
$function$;

create or replace function public.save_dynamic_availability_shadow_submission(
  requested_job_type_id uuid,
  requested_year integer,
  requested_month integer,
  requested_user_id uuid,
  requested_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  current_user_id uuid:=auth.uid();
  job public.job_types%rowtype;
  period public.dynamic_availability_periods%rowtype;
  v_submission_id uuid;
  entry_item jsonb;
  allowed_statuses jsonb;
  requested_status text;
begin
  if current_user_id is null then raise exception 'not authenticated'; end if;
  if not public.has_dynamic_job_type_permission('availability.manage_submissions', requested_job_type_id, current_user_id) then raise exception 'not allowed'; end if;
  select * into job from public.job_types where id=requested_job_type_id;
  if job.id is null then raise exception 'job type not found'; end if;
  if not exists(select 1 from public.job_type_memberships m where m.job_type_id=job.id and m.user_id=requested_user_id) then raise exception 'user is not a member of this job type'; end if;
  select * into period from public.dynamic_availability_periods where job_type_id=job.id and year=requested_year and month=requested_month;
  if period.id is null then raise exception 'shadow period not materialized'; end if;

  insert into public.dynamic_availability_submissions(period_id,user_id,status,min_shifts,target_shifts,max_shifts,max_nights,max_weekends,max_holidays,note,submitted_at)
  values(period.id,requested_user_id,coalesce(requested_payload->>'submissionStatus','draft'),
    nullif(requested_payload->>'minimum','')::integer,nullif(requested_payload->>'target','')::integer,nullif(requested_payload->>'maximum','')::integer,
    nullif(requested_payload->>'maxNights','')::integer,nullif(requested_payload->>'maxWeekends','')::integer,nullif(requested_payload->>'maxHolidays','')::integer,
    nullif(trim(coalesce(requested_payload->>'note','')),''),case when coalesce(requested_payload->>'submissionStatus','draft')='submitted' then now() else null end)
  on conflict(period_id,user_id) do update set
    status=excluded.status,min_shifts=excluded.min_shifts,target_shifts=excluded.target_shifts,max_shifts=excluded.max_shifts,
    max_nights=excluded.max_nights,max_weekends=excluded.max_weekends,max_holidays=excluded.max_holidays,note=excluded.note,
    submitted_at=excluded.submitted_at,updated_at=now()
  returning id into v_submission_id;

  allowed_statuses:=coalesce(job.availability_config->'statuses','["available","unavailable"]'::jsonb);
  for entry_item in select value from jsonb_array_elements(coalesce(requested_payload->'entries','[]'::jsonb)) loop
    requested_status:=entry_item->>'status';
    if not (allowed_statuses ? requested_status) then raise exception 'availability status % is not enabled for this job type',requested_status; end if;
    if not exists(select 1 from public.dynamic_availability_slots s where s.id=(entry_item->>'slotId')::uuid and s.period_id=period.id) then raise exception 'slot does not belong to period'; end if;
    insert into public.dynamic_availability_entries(submission_id,slot_id,availability_status,note)
    values(v_submission_id,(entry_item->>'slotId')::uuid,requested_status,nullif(trim(coalesce(entry_item->>'note','')),''))
    on conflict on constraint dynamic_availability_entries_pkey do update
      set availability_status=excluded.availability_status,note=excluded.note,updated_at=now();
  end loop;

  return jsonb_build_object('saved',true,'mode','shadow','submissionId',v_submission_id);
end;
$function$;

-- Deadline edits are part of opening/managing an availability period; no legacy fallback.
create or replace function public.set_dynamic_period_submission_deadline(
  requested_job_type_id uuid, requested_year integer, requested_month integer, requested_deadline timestamptz
) returns void
language plpgsql security definer set search_path=public as $$
declare actor uuid := auth.uid(); target_period public.dynamic_availability_periods%rowtype;
begin
  if actor is null then raise exception 'not authenticated'; end if;
  if not public.has_dynamic_job_type_permission('availability.open_period', requested_job_type_id, actor) then raise exception 'not allowed'; end if;
  select * into target_period from public.dynamic_availability_periods ap
  where ap.job_type_id=requested_job_type_id and ap.year=requested_year and ap.month=requested_month;
  if target_period.id is null then raise exception 'dynamic period not found'; end if;
  if target_period.status='archived' then raise exception 'archived period cannot be changed'; end if;
  update public.dynamic_availability_periods set submission_deadline=requested_deadline,updated_at=now() where id=target_period.id;
  insert into public.audit_logs(action,actor_user_id,entity_type,entity_id,summary,metadata)
  values('system_event',actor,'dynamic_availability_period',target_period.id,'מועד אחרון להגשת אילוצים עודכן',
    jsonb_build_object('job_type_id',requested_job_type_id,'year',requested_year,'month',requested_month,'submission_deadline',requested_deadline));
end; $$;

-- Keep execute rights explicit after replacements.
grant execute on function public.create_dynamic_availability_shadow_period(uuid,integer,integer) to authenticated;
grant execute on function public.set_dynamic_period_status(uuid,integer,integer,text) to authenticated;
grant execute on function public.get_dynamic_period_workflow(uuid,integer,integer) to authenticated;
grant execute on function public.create_dynamic_schedule_shadow_draft(uuid,integer,integer) to authenticated;
grant execute on function public.create_dynamic_monthly_rotation_draft(uuid,integer,integer) to authenticated;
grant execute on function public.get_dynamic_schedule_draft_editor(uuid) to authenticated;
grant execute on function public.set_dynamic_schedule_draft_assignment(uuid,uuid,uuid,uuid,text) to authenticated;
grant execute on function public.remove_dynamic_schedule_draft_assignment(uuid,uuid) to authenticated;
grant execute on function public.set_dynamic_schedule_slot_intentionally_unassigned(uuid,uuid,integer,text) to authenticated;
grant execute on function public.publish_dynamic_schedule_draft(uuid) to authenticated;
grant execute on function public.get_dynamic_published_schedule_editor(uuid) to authenticated;
grant execute on function public.set_dynamic_published_schedule_assignment(uuid,uuid,uuid,uuid,text) to authenticated;
grant execute on function public.get_dynamic_availability_shadow_workspace(uuid,integer,integer) to authenticated;
grant execute on function public.save_dynamic_availability_shadow_submission(uuid,integer,integer,uuid,jsonb) to authenticated;
grant execute on function public.set_dynamic_period_submission_deadline(uuid,integer,integer,timestamptz) to authenticated;


create or replace function public.get_dynamic_shifts_management_workspace(
  requested_year integer,
  requested_month integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  actor_role text;
begin
  if actor is null then raise exception 'not authenticated'; end if;
  if requested_year not between 2020 and 2100 or requested_month not between 1 and 12 then
    raise exception 'invalid year or month';
  end if;

  select p.role::text into actor_role
  from public.profiles p
  where p.id = actor and p.is_active = true;
  if actor_role is null then raise exception 'user not active'; end if;

  if not exists (
    select 1
    from public.job_types jt
    where jt.is_active = true
      and (
        public.has_dynamic_job_type_permission('availability.view_team', jt.id, actor)
        or public.has_dynamic_job_type_permission('availability.open_period', jt.id, actor)
        or public.has_dynamic_job_type_permission('availability.close_period', jt.id, actor)
        or public.has_dynamic_job_type_permission('availability.manage_submissions', jt.id, actor)
        or public.has_dynamic_job_type_permission('schedule.view_team', jt.id, actor)
        or public.has_dynamic_job_type_permission('schedule.create_draft', jt.id, actor)
        or public.has_dynamic_job_type_permission('schedule.edit_draft', jt.id, actor)
        or public.has_dynamic_job_type_permission('schedule.publish', jt.id, actor)
        or public.has_dynamic_job_type_permission('schedule.edit_published', jt.id, actor)
        or public.has_dynamic_job_type_permission('rotation.generate', jt.id, actor)
      )
  ) then
    raise exception 'not allowed';
  end if;

  return jsonb_build_object(
    'year', requested_year,
    'month', requested_month,
    'generatedAt', now(),
    'roles', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'jobType', public.dynamic_job_type_live_snapshot(jt.id),
          'isExplicitManager', exists (
            select 1 from public.job_type_managers jm
            where jm.user_id = actor and jm.job_type_id = jt.id
          ),
          'accessSource', case
            when actor_role = 'admin' then 'system_admin'
            else 'job_type_manager'
          end,
          'workflow', jsonb_build_object(
            'jobTypeId', jt.id,
            'jobTypeName', jt.name,
            'year', requested_year,
            'month', requested_month,
            'memberCount', (
              select count(*)::integer
              from public.job_type_memberships m
              join public.profiles p on p.id = m.user_id and p.is_active = true
              where m.job_type_id = jt.id
            ),
            'availabilityEnabled', coalesce((jt.availability_config->>'enabled')::boolean, false),
            'schedulingStrategy', coalesce(jt.scheduling_strategy, jt.scheduling_config->>'schedulingStrategy', 'availability_optimizer'),
            'period', (
              select jsonb_build_object(
                'id', ap.id,
                'status', ap.status,
                'title', ap.title,
                'submissionDeadline', ap.submission_deadline,
                'slotCount', (select count(*)::integer from public.dynamic_availability_slots s where s.period_id = ap.id),
                'submissionCount', (select count(*)::integer from public.dynamic_availability_submissions sub where sub.period_id = ap.id),
                'submittedCount', (select count(*)::integer from public.dynamic_availability_submissions sub where sub.period_id = ap.id and sub.status = 'submitted')
              )
              from public.dynamic_availability_periods ap
              where ap.job_type_id = jt.id and ap.year = requested_year and ap.month = requested_month
              limit 1
            ),
            'draft', (
              select jsonb_build_object('id', d.id, 'status', d.status, 'metrics', d.metrics, 'createdAt', d.created_at, 'updatedAt', d.updated_at)
              from public.dynamic_schedule_shadow_drafts d
              where d.job_type_id = jt.id and d.year = requested_year and d.month = requested_month
              order by d.created_at desc limit 1
            ),
            'publication', (
              select jsonb_build_object(
                'id', pub.id,
                'status', pub.status,
                'publishedAt', pub.published_at,
                'assignmentCount', (select count(*)::integer from public.dynamic_schedule_published_assignments a where a.publication_id = pub.id)
              )
              from public.dynamic_schedule_publications pub
              where pub.job_type_id = jt.id and pub.year = requested_year and pub.month = requested_month
              limit 1
            )
          )
        ) order by jt.name
      )
      from public.job_types jt
      where jt.is_active = true
        and (
          public.has_dynamic_job_type_permission('availability.view_team', jt.id, actor)
          or public.has_dynamic_job_type_permission('availability.open_period', jt.id, actor)
          or public.has_dynamic_job_type_permission('availability.close_period', jt.id, actor)
          or public.has_dynamic_job_type_permission('availability.manage_submissions', jt.id, actor)
          or public.has_dynamic_job_type_permission('schedule.view_team', jt.id, actor)
          or public.has_dynamic_job_type_permission('schedule.create_draft', jt.id, actor)
          or public.has_dynamic_job_type_permission('schedule.edit_draft', jt.id, actor)
          or public.has_dynamic_job_type_permission('schedule.publish', jt.id, actor)
          or public.has_dynamic_job_type_permission('schedule.edit_published', jt.id, actor)
          or public.has_dynamic_job_type_permission('rotation.generate', jt.id, actor)
        )
    ), '[]'::jsonb)
  );
end;
$$;

grant execute on function public.get_dynamic_shifts_management_workspace(integer,integer) to authenticated;

commit;
