import { useEffect, useState } from 'react';
import { BellRing, Clock3, TimerReset } from 'lucide-react';
import { activityTrackingService } from '../../services/activityTrackingService';
import type { ActivityPersonalSettingsRole } from '../../types/activityTracking';

const minutesLabel=(value:number)=>value<60?`${value} דקות`:value%60===0?`${value/60} שעות`:`${Math.floor(value/60)}:${String(value%60).padStart(2,'0')} שעות`;
const effective=(personal:boolean|null, fallback:boolean)=>personal===null?fallback:personal;
const sourceLabel=(personal:boolean|null)=>personal===null?'ברירת המחדל של התפקיד':'הגדרה אישית';

export default function ActivityTrackingPersonalSettings(){
 const[roles,setRoles]=useState<ActivityPersonalSettingsRole[]>([]);const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState('');
 useEffect(()=>{void activityTrackingService.getMySettings().then(setRoles).catch(e=>console.error('Activity settings failed:',e))},[]);
 if(!roles.length)return null;
 const patch=(id:string,changes:Partial<ActivityPersonalSettingsRole['personal']>)=>setRoles(v=>v.map(r=>r.jobTypeId===id?{...r,personal:{...r.personal,...changes}}:r));
 const save=async(r:ActivityPersonalSettingsRole)=>{setBusy(r.jobTypeId);setMessage('');try{await activityTrackingService.saveMySettings(r.jobTypeId,r.personal);setRoles(await activityTrackingService.getMySettings());setMessage('הגדרות מעקב הפעילות נשמרו.')}catch(e){setMessage(e instanceof Error?e.message:'שמירת ההגדרות נכשלה.')}finally{setBusy(null)}};
 const reset=async(r:ActivityPersonalSettingsRole)=>{setBusy(r.jobTypeId);setMessage('');try{await activityTrackingService.resetMySettings(r.jobTypeId);setRoles(await activityTrackingService.getMySettings());setMessage('חזרת לברירת המחדל של התפקיד.')}finally{setBusy(null)}};
 return <div className="activity-personal-settings"><div className="settings-subsection-heading"><Clock3 size={20}/><div><h3>מעקב פעילות</h3><p>אפשר להתאים את מדיניות הטיימר האישית. בכל כרטיס מוצג גם מה הוגדר כברירת המחדל של התפקיד.</p></div></div>{roles.map(r=>{
  const autoEnd=effective(r.personal.autoEndEnabled,r.defaults.autoEndEnabled);
  const endReminder=effective(r.personal.endReminderEnabled,r.defaults.endReminderEnabled);
  const continuous=effective(r.personal.continuousReminderEnabled,r.defaults.continuousReminderEnabled);
  const autoEndTime=r.personal.autoEndTime??r.defaults.autoEndTime;
  const endMinutes=r.personal.endReminderMinutesBefore??r.defaults.endReminderMinutesBefore;
  const continuousMinutes=r.personal.continuousReminderMinutes??r.defaults.continuousReminderMinutes;
  return <section className="settings-reminder-card activity-policy-role" key={r.jobTypeId}><div className="settings-reminder-card-heading"><div><strong>{r.jobTypeName}</strong><span>שינויים אישיים גוברים על ברירת המחדל של התפקיד. אפשר לחזור אליה בכל עת.</span></div></div><div className="activity-policy-cards">
   <article className="activity-policy-card"><div className="activity-policy-card-title"><Clock3 size={19}/><div><strong>סיום יום אוטומטי</strong><span>אם לא לחצת על „סיום יום”, המערכת תסגור את הפעילות בשעה שנקבעה.</span></div></div><div className="activity-policy-default">ברירת המחדל של התפקיד: <strong>{r.defaults.autoEndEnabled?`פעיל · ${r.defaults.autoEndTime}`:'כבוי'}</strong></div><label className="activity-policy-toggle"><input type="checkbox" checked={autoEnd} onChange={e=>patch(r.jobTypeId,{autoEndEnabled:e.target.checked})}/><span>{autoEnd?'פעיל':'כבוי'}</span><small>{sourceLabel(r.personal.autoEndEnabled)}</small></label>{autoEnd?<label className="activity-policy-field"><span>שעת סיום</span><input type="time" value={autoEndTime} onChange={e=>patch(r.jobTypeId,{autoEndTime:e.target.value})}/></label>:null}</article>
   <article className={`activity-policy-card ${!autoEnd?'activity-policy-card-disabled':''}`}><div className="activity-policy-card-title"><BellRing size={19}/><div><strong>תזכורת לפני סיום היום</strong><span>התראה לפני שהמערכת מסיימת את היום אוטומטית.</span></div></div><div className="activity-policy-default">ברירת המחדל של התפקיד: <strong>{r.defaults.endReminderEnabled?`פעילה · ${minutesLabel(r.defaults.endReminderMinutesBefore)} לפני`:'כבויה'}</strong></div>{autoEnd?<><label className="activity-policy-toggle"><input type="checkbox" checked={endReminder} onChange={e=>patch(r.jobTypeId,{endReminderEnabled:e.target.checked})}/><span>{endReminder?'פעילה':'כבויה'}</span><small>{sourceLabel(r.personal.endReminderEnabled)}</small></label>{endReminder?<label className="activity-policy-field"><span>כמה זמן לפני</span><select value={endMinutes} onChange={e=>patch(r.jobTypeId,{endReminderMinutesBefore:Number(e.target.value)})}>{[5,10,15,30,45,60,90,120].map(v=><option key={v} value={v}>{minutesLabel(v)}</option>)}</select></label>:null}</>:<p className="activity-policy-unavailable">זמין כאשר סיום יום אוטומטי פעיל.</p>}</article>
   <article className="activity-policy-card"><div className="activity-policy-card-title"><TimerReset size={19}/><div><strong>התראה על פעילות ממושכת</strong><span>אם אותה פעילות רצה זמן רב ברצף, נזכיר לבדוק שלא שכחת להחליף או להשהות אותה.</span></div></div><div className="activity-policy-default">ברירת המחדל של התפקיד: <strong>{r.defaults.continuousReminderEnabled?`פעילה · אחרי ${minutesLabel(r.defaults.continuousReminderMinutes)}`:'כבויה'}</strong></div><label className="activity-policy-toggle"><input type="checkbox" checked={continuous} onChange={e=>patch(r.jobTypeId,{continuousReminderEnabled:e.target.checked})}/><span>{continuous?'פעילה':'כבויה'}</span><small>{sourceLabel(r.personal.continuousReminderEnabled)}</small></label>{continuous?<label className="activity-policy-field"><span>התרע לאחר</span><select value={continuousMinutes} onChange={e=>patch(r.jobTypeId,{continuousReminderMinutes:Number(e.target.value)})}>{[60,120,180,240,300,360,480].map(v=><option key={v} value={v}>{minutesLabel(v)}</option>)}</select></label>:null}</article>
  </div><div className="activity-personal-settings-actions"><button type="button" className="secondary-button" disabled={busy===r.jobTypeId} onClick={()=>void reset(r)}>חזרה לברירת המחדל של התפקיד</button><button type="button" className="primary-button" disabled={busy===r.jobTypeId} onClick={()=>void save(r)}>שמור</button></div></section>})}{message?<p className="settings-inline-message">{message}</p>:null}</div>;
}
